// PRC-04 R2: builds backend/app/practice/umalqura.py, the Umm al-Qura month
// table the server uses to check sighting announcements (±1 day from the
// expected start). The table comes from the same `islamic-umalqura` calendar
// the app uses on the device (Intl / ICU), so server and app always agree.
//
//   node content/practice/build_umalqura.mjs   (from the repo root)
import { writeFileSync } from "node:fs"

const FIRST = 1440
const LAST = 1600 // ICU's Umm al-Qura data ends with 1600 AH

const fmt = new Intl.DateTimeFormat("en-u-ca-islamic-umalqura-nu-latn", { timeZone: "UTC", year: "numeric", month: "numeric", day: "numeric" })
const hijri = (t) => {
  const parts = fmt.formatToParts(new Date(t))
  const get = (k) => parseInt(parts.find((p) => p.type === k)?.value ?? "0", 10)
  return [get("relatedYear") || get("year"), get("month"), get("day")]
}

const DAY = 86_400_000
const starts = []
for (let t = Date.UTC(2018, 7, 1, 12); t < Date.UTC(2180, 0, 1, 12); t += DAY) {
  const [y, m, d] = hijri(t)
  if (d === 1) starts.push([y, m, new Date(t).toISOString().slice(0, 10)])
}

const years = {}
for (let i = 0; i < starts.length - 1; i++) {
  const [y, m, s] = starts[i]
  const len = Math.round((Date.parse(starts[i + 1][2]) - Date.parse(s)) / DAY)
  years[y] ??= { start: null, bits: "" }
  if (m === 1) years[y].start = s
  years[y].bits += len === 30 ? "1" : len === 29 ? "0" : "?"
}

const rows = []
for (let y = FIRST; y <= LAST; y++) {
  const r = years[y]
  if (!r?.start || r.bits.length !== 12 || r.bits.includes("?")) throw new Error(`incomplete year ${y}`)
  rows.push(`    ${y}: ("${r.start}", "${r.bits}"),`)
}

const py = `"""PRC-04 R2: the Umm al-Qura calendar on the server, used only to check a
sighting announcement against the expected first day of its month (±1 day),
so the server never trusts a caller's "expected" date.

Generated by content/practice/build_umalqura.mjs — do not edit by hand. Per
Hijri year: the civil date of 1 Muharram and the lengths of its 12 months
("1" = 30 days, "0" = 29), from the same \`islamic-umalqura\` calendar the app
uses on the device (Intl; ICU ${process.versions.icu} / CLDR ${process.versions.cldr}; ICU data under
the Unicode License v3). It matches the official Umm al-Qura calendar on
every date checked (docs/agents/research/06 §3).
"""

from datetime import date, timedelta

# year: (1 Muharram, month lengths 1..12)
_YEARS: dict[int, tuple[str, str]] = {
${rows.join("\n")}
}

FIRST_YEAR, LAST_YEAR = min(_YEARS), max(_YEARS)


def month_start(hijri_year: int, hijri_month: int) -> date | None:
    """The expected civil date of day 1 of a Hijri month, or None outside the table."""
    row = _YEARS.get(hijri_year)
    if row is None or not 1 <= hijri_month <= 12:
        return None
    start, lengths = row
    days = sum(30 if bit == "1" else 29 for bit in lengths[: hijri_month - 1])
    return date.fromisoformat(start) + timedelta(days=days)
`

writeFileSync(new URL("../../backend/app/practice/umalqura.py", import.meta.url), py)
console.log(`wrote ${rows.length} years (${FIRST}–${LAST})`)
