"""knw-05 approval snapshots and review history

Revision ID: 4206e7276135
Revises: 8767115d9f7b
Create Date: 2026-10-05 21:03:00.309571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4206e7276135'
down_revision: Union[str, Sequence[str], None] = '8767115d9f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knw_reviews',
    sa.Column('item_type', sa.String(length=24), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_knw_reviews_reviewer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knw_reviews'))
    )
    op.create_index('ix_knw_reviews_item', 'knw_reviews', ['item_type', 'item_id', 'lang'], unique=False)
    op.add_column('content_approvals', sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_approvals', 'snapshot')
    op.drop_index('ix_knw_reviews_item', table_name='knw_reviews')
    op.drop_table('knw_reviews')
    # ### end Alembic commands ###
