"""initial schema

Revision ID: 8767115d9f7b
Revises: 
Create Date: 2026-10-05 20:44:08.116399

"""
from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8767115d9f7b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knw_ai_calls',
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knw_ai_calls'))
    )
    op.create_index(op.f('ix_knw_ai_calls_at'), 'knw_ai_calls', ['at'], unique=False)
    op.create_table('knw_answer_log',
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('route', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=1), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knw_answer_log'))
    )
    op.create_index(op.f('ix_knw_answer_log_at'), 'knw_answer_log', ['at'], unique=False)
    op.create_table('knw_eval_runs',
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knw_eval_runs'))
    )
    op.create_table('knw_explanation_log',
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exercise_id', sa.String(length=24), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knw_explanation_log'))
    )
    op.create_index(op.f('ix_knw_explanation_log_exercise_id'), 'knw_explanation_log', ['exercise_id'], unique=False)
    op.create_table('knw_glossary',
    sa.Column('concept', sa.String(length=64), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('term', sa.String(length=120), nullable=False),
    sa.Column('alternates', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('source_ids', postgresql.ARRAY(sa.String(length=96)), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knw_glossary'))
    )
    op.create_index('uq_knw_glossary_approved', 'knw_glossary', ['concept', 'lang'], unique=True, postgresql_where="status = 'approved'")
    op.create_table('knw_library_items',
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=16), nullable=False),
    sa.Column('origin_url', sa.String(length=400), nullable=False),
    sa.Column('file_url', sa.String(length=600), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('thumbnail_reviewed', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knw_library_items'))
    )
    op.create_index(op.f('ix_knw_library_items_external_id'), 'knw_library_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_knw_library_items_lang'), 'knw_library_items', ['lang'], unique=False)
    op.create_table('knw_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('license', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knw_sources'))
    )
    op.create_table('mot_anon_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('install_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('lesson_id', sa.String(length=16), nullable=True),
    sa.Column('unit_id', sa.String(length=8), nullable=True),
    sa.Column('objective_id', sa.String(length=24), nullable=True),
    sa.Column('exercise_id', sa.String(length=24), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('context', sa.String(length=16), nullable=True),
    sa.Column('shown', sa.String(length=16), nullable=True),
    sa.Column('is_repeat', sa.Boolean(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mot_anon_events'))
    )
    op.create_index(op.f('ix_mot_anon_events_day'), 'mot_anon_events', ['day'], unique=False)
    op.create_index(op.f('ix_mot_anon_events_install_id'), 'mot_anon_events', ['install_id'], unique=False)
    op.create_index(op.f('ix_mot_anon_events_type'), 'mot_anon_events', ['type'], unique=False)
    op.create_table('mot_daily_snapshots',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('day', name=op.f('pk_mot_daily_snapshots'))
    )
    op.create_table('mot_release_markers',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mot_release_markers'))
    )
    op.create_table('outbox',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_index(op.f('ix_outbox_name'), 'outbox', ['name'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.String(length=5)), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cmp_groups',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('mentor_id', sa.UUID(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], name=op.f('fk_cmp_groups_mentor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cmp_groups')),
    sa.UniqueConstraint('join_code', name=op.f('uq_cmp_groups_join_code'))
    )
    op.create_index(op.f('ix_cmp_groups_mentor_id'), 'cmp_groups', ['mentor_id'], unique=False)
    op.create_table('cmp_help_requests',
    sa.Column('learner_id', sa.UUID(), nullable=True),
    sa.Column('guest_token_hash', sa.String(length=64), nullable=True),
    sa.Column('handle', sa.String(length=40), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('mentor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], name=op.f('fk_cmp_help_requests_learner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], name=op.f('fk_cmp_help_requests_mentor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cmp_help_requests'))
    )
    op.create_index(op.f('ix_cmp_help_requests_guest_token_hash'), 'cmp_help_requests', ['guest_token_hash'], unique=False)
    op.create_index(op.f('ix_cmp_help_requests_learner_id'), 'cmp_help_requests', ['learner_id'], unique=False)
    op.create_index(op.f('ix_cmp_help_requests_mentor_id'), 'cmp_help_requests', ['mentor_id'], unique=False)
    op.create_table('cmp_mentor_links',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('mentor_id', sa.UUID(), nullable=False),
    sa.Column('share_progress', sa.Boolean(), nullable=False),
    sa.Column('chosen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], name=op.f('fk_cmp_mentor_links_learner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], name=op.f('fk_cmp_mentor_links_mentor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id', name=op.f('pk_cmp_mentor_links'))
    )
    op.create_index(op.f('ix_cmp_mentor_links_mentor_id'), 'cmp_mentor_links', ['mentor_id'], unique=False)
    op.create_table('cmp_mentor_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('availability', sa.String(length=120), nullable=False),
    sa.Column('accepting', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cmp_mentor_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_cmp_mentor_profiles'))
    )
    op.create_table('cmp_reports',
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('handled_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], name=op.f('fk_cmp_reports_handled_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_cmp_reports_reporter_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cmp_reports'))
    )
    op.create_table('content_approvals',
    sa.Column('item_type', sa.String(length=24), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_content_approvals_reviewer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_approvals')),
    sa.UniqueConstraint('item_type', 'item_id', 'lang', name=op.f('uq_content_approvals_item_type'))
    )
    op.create_table('invites',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('used_by', sa.UUID(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_invites_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], name=op.f('fk_invites_used_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_invites'))
    )
    op.create_table('knw_eval_answers',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=12), nullable=False),
    sa.Column('system', sa.String(length=8), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['knw_eval_runs.id'], name=op.f('fk_knw_eval_answers_run_id_knw_eval_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knw_eval_answers'))
    )
    op.create_index(op.f('ix_knw_eval_answers_run_id'), 'knw_eval_answers', ['run_id'], unique=False)
    op.create_table('knw_passages',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ref_key', sa.String(length=64), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('context_text', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('origin_url', sa.String(length=400), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text_hash', sa.String(length=80), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knw_sources.id'], name=op.f('fk_knw_passages_source_id_knw_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knw_passages'))
    )
    op.create_index('ix_knw_passages_embedding', 'knw_passages', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_knw_passages_lang_kind', 'knw_passages', ['lang', 'kind'], unique=False)
    op.create_index(op.f('ix_knw_passages_ref_key'), 'knw_passages', ['ref_key'], unique=False)
    op.create_index(op.f('ix_knw_passages_source_id'), 'knw_passages', ['source_id'], unique=False)
    op.create_table('knw_saved_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('ref_id', sa.String(length=96), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_knw_saved_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'kind', 'ref_id', name=op.f('pk_knw_saved_items'))
    )
    op.create_table('lrn_explanation_blocks',
    sa.Column('exercise_id', sa.String(length=24), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('blocked_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], name=op.f('fk_lrn_explanation_blocks_blocked_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('exercise_id', 'lang', name=op.f('pk_lrn_explanation_blocks'))
    )
    op.create_table('lrn_lesson_completions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.String(length=16), nullable=False),
    sa.Column('first_completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('times', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lrn_lesson_completions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'lesson_id', name=op.f('pk_lrn_lesson_completions'))
    )
    op.create_table('lrn_objective_mastery',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.String(length=24), nullable=False),
    sa.Column('p', sa.Float(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('last_answer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_exercise_id', sa.String(length=24), nullable=True),
    sa.Column('checks_done', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lrn_objective_mastery_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'objective_id', name=op.f('pk_lrn_objective_mastery'))
    )
    op.create_table('lrn_unit_unlocks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lrn_unit_unlocks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'unit_id', name=op.f('pk_lrn_unit_unlocks'))
    )
    op.create_table('mot_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.String(length=24), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mot_badges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'badge_id', name=op.f('pk_mot_badges'))
    )
    op.create_table('mot_challenge_templates',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_mot_challenge_templates_approved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mot_challenge_templates'))
    )
    op.create_table('mot_challenges',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=16), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_lang', sa.String(length=5), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_mot_challenges_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mot_challenges'))
    )
    op.create_index(op.f('ix_mot_challenges_group_id'), 'mot_challenges', ['group_id'], unique=False)
    op.create_table('mot_engagement',
    sa.Column('install_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('first_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mot_engagement_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('install_id', name=op.f('pk_mot_engagement'))
    )
    op.create_index(op.f('ix_mot_engagement_user_id'), 'mot_engagement', ['user_id'], unique=False)
    op.create_table('mot_group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mot_group_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_mot_group_members'))
    )
    op.create_table('mot_learning_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('item_id', sa.String(length=16), nullable=True),
    sa.Column('is_repeat', sa.Boolean(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mot_learning_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mot_learning_log'))
    )
    op.create_index(op.f('ix_mot_learning_log_user_id'), 'mot_learning_log', ['user_id'], unique=False)
    op.create_table('mot_streak_days',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mot_streak_days_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day', name=op.f('pk_mot_streak_days'))
    )
    op.create_table('one_time_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('pending_email', sa.String(length=254), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_one_time_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_one_time_codes'))
    )
    op.create_index(op.f('ix_one_time_codes_user_id'), 'one_time_codes', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('endpoint', sa.String(length=1024), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('install_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('ignored_in_row', sa.Integer(), nullable=False),
    sa.Column('last_reminder_on', sa.String(length=10), nullable=True),
    sa.Column('last_learned_on', sa.String(length=10), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    op.create_index(op.f('ix_push_subscriptions_install_id'), 'push_subscriptions', ['install_id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_sessions_token_hash'))
    )
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('cmp_group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cmp_groups.id'], name=op.f('fk_cmp_group_members_group_id_cmp_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cmp_group_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_cmp_group_members'))
    )
    op.create_table('cmp_group_messages',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_cmp_group_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['cmp_groups.id'], name=op.f('fk_cmp_group_messages_group_id_cmp_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cmp_group_messages'))
    )
    op.create_index(op.f('ix_cmp_group_messages_group_id'), 'cmp_group_messages', ['group_id'], unique=False)
    op.create_table('cmp_help_messages',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=8), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_cmp_help_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['cmp_help_requests.id'], name=op.f('fk_cmp_help_messages_request_id_cmp_help_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cmp_help_messages'))
    )
    op.create_index(op.f('ix_cmp_help_messages_request_id'), 'cmp_help_messages', ['request_id'], unique=False)
    op.create_table('mot_challenge_checks',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['mot_challenges.id'], name=op.f('fk_mot_challenge_checks_challenge_id_mot_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mot_challenge_checks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('challenge_id', 'user_id', name=op.f('pk_mot_challenge_checks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mot_challenge_checks')
    op.drop_index(op.f('ix_cmp_help_messages_request_id'), table_name='cmp_help_messages')
    op.drop_table('cmp_help_messages')
    op.drop_index(op.f('ix_cmp_group_messages_group_id'), table_name='cmp_group_messages')
    op.drop_table('cmp_group_messages')
    op.drop_table('cmp_group_members')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_install_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_one_time_codes_user_id'), table_name='one_time_codes')
    op.drop_table('one_time_codes')
    op.drop_table('mot_streak_days')
    op.drop_index(op.f('ix_mot_learning_log_user_id'), table_name='mot_learning_log')
    op.drop_table('mot_learning_log')
    op.drop_table('mot_group_members')
    op.drop_index(op.f('ix_mot_engagement_user_id'), table_name='mot_engagement')
    op.drop_table('mot_engagement')
    op.drop_index(op.f('ix_mot_challenges_group_id'), table_name='mot_challenges')
    op.drop_table('mot_challenges')
    op.drop_table('mot_challenge_templates')
    op.drop_table('mot_badges')
    op.drop_table('lrn_unit_unlocks')
    op.drop_table('lrn_objective_mastery')
    op.drop_table('lrn_lesson_completions')
    op.drop_table('lrn_explanation_blocks')
    op.drop_table('knw_saved_items')
    op.drop_index(op.f('ix_knw_passages_source_id'), table_name='knw_passages')
    op.drop_index(op.f('ix_knw_passages_ref_key'), table_name='knw_passages')
    op.drop_index('ix_knw_passages_lang_kind', table_name='knw_passages')
    op.drop_index('ix_knw_passages_embedding', table_name='knw_passages', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('knw_passages')
    op.drop_index(op.f('ix_knw_eval_answers_run_id'), table_name='knw_eval_answers')
    op.drop_table('knw_eval_answers')
    op.drop_table('invites')
    op.drop_table('content_approvals')
    op.drop_table('cmp_reports')
    op.drop_table('cmp_mentor_profiles')
    op.drop_index(op.f('ix_cmp_mentor_links_mentor_id'), table_name='cmp_mentor_links')
    op.drop_table('cmp_mentor_links')
    op.drop_index(op.f('ix_cmp_help_requests_mentor_id'), table_name='cmp_help_requests')
    op.drop_index(op.f('ix_cmp_help_requests_learner_id'), table_name='cmp_help_requests')
    op.drop_index(op.f('ix_cmp_help_requests_guest_token_hash'), table_name='cmp_help_requests')
    op.drop_table('cmp_help_requests')
    op.drop_index(op.f('ix_cmp_groups_mentor_id'), table_name='cmp_groups')
    op.drop_table('cmp_groups')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outbox_name'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_table('mot_release_markers')
    op.drop_table('mot_daily_snapshots')
    op.drop_index(op.f('ix_mot_anon_events_type'), table_name='mot_anon_events')
    op.drop_index(op.f('ix_mot_anon_events_install_id'), table_name='mot_anon_events')
    op.drop_index(op.f('ix_mot_anon_events_day'), table_name='mot_anon_events')
    op.drop_table('mot_anon_events')
    op.drop_table('knw_sources')
    op.drop_index(op.f('ix_knw_library_items_lang'), table_name='knw_library_items')
    op.drop_index(op.f('ix_knw_library_items_external_id'), table_name='knw_library_items')
    op.drop_table('knw_library_items')
    op.drop_index('uq_knw_glossary_approved', table_name='knw_glossary', postgresql_where="status = 'approved'")
    op.drop_table('knw_glossary')
    op.drop_index(op.f('ix_knw_explanation_log_exercise_id'), table_name='knw_explanation_log')
    op.drop_table('knw_explanation_log')
    op.drop_table('knw_eval_runs')
    op.drop_index(op.f('ix_knw_answer_log_at'), table_name='knw_answer_log')
    op.drop_table('knw_answer_log')
    op.drop_index(op.f('ix_knw_ai_calls_at'), table_name='knw_ai_calls')
    op.drop_table('knw_ai_calls')
    # ### end Alembic commands ###
