"""knw-01 reliability §7, §14.5: ask_id tracing on knw_answer_log and
knw_ai_calls, plus the public reason, internal detail, entry point and a
stage trace (no question or answer text). Additive and nullable only, so
older rows stay valid and the previous image still runs on this schema.
Rollback is the previous image or feature flags, never this downgrade
(it would drop diagnostic data).

Revision ID: ef83fa7deee6
Revises: d1e2f3a4b5c6
Create Date: 2026-10-06 14:13:10.766774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef83fa7deee6'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knw_ai_calls', sa.Column('ask_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_knw_ai_calls_ask_id'), 'knw_ai_calls', ['ask_id'], unique=False)
    op.add_column('knw_answer_log', sa.Column('ask_id', sa.String(length=32), nullable=True))
    op.add_column('knw_answer_log', sa.Column('reason_code', sa.String(length=32), nullable=True))
    op.add_column('knw_answer_log', sa.Column('detail', sa.String(length=48), nullable=True))
    op.add_column('knw_answer_log', sa.Column('entrypoint', sa.String(length=12), nullable=True))
    op.add_column('knw_answer_log', sa.Column('suggestion_id', sa.String(length=48), nullable=True))
    op.add_column('knw_answer_log', sa.Column('client_request_id', sa.String(length=64), nullable=True))
    op.add_column('knw_answer_log', sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_knw_answer_log_ask_id'), 'knw_answer_log', ['ask_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knw_answer_log_ask_id'), table_name='knw_answer_log')
    op.drop_column('knw_answer_log', 'trace')
    op.drop_column('knw_answer_log', 'client_request_id')
    op.drop_column('knw_answer_log', 'suggestion_id')
    op.drop_column('knw_answer_log', 'entrypoint')
    op.drop_column('knw_answer_log', 'detail')
    op.drop_column('knw_answer_log', 'reason_code')
    op.drop_column('knw_answer_log', 'ask_id')
    op.drop_index(op.f('ix_knw_ai_calls_ask_id'), table_name='knw_ai_calls')
    op.drop_column('knw_ai_calls', 'ask_id')
    # ### end Alembic commands ###
