"""List the wording differences between the spreadsheet (ar/en) and the official site (ar/en).

Usage: python3 tools/compare_sheet_site.py   -> writes tools/sheet_vs_site.txt
Sentences are compared with harakat, punctuation, list markers and spacing ignored, so the
report shows only differences in letters/words. Harakat-only differences are counted, not listed.
"""
import difflib, os, re, unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
SHEET_FIRST_ROW = 14          # rows 1-13 are the title page and introduction (not on the site)


def lines(name, sheet):
    with open(os.path.join(HERE, 'source', name), encoding='utf-8') as f:
        ls = f.read().split('\n')
    out = []
    for i, l in enumerate(ls, 1):
        if sheet and i < SHEET_FIRST_ROW:
            continue
        if re.match(r'^(## SECTION|\[TAB |\[IMG |\[NAV |#h2 )', l) or not l.strip():
            continue
        out.append((i, re.sub(r'^#h\d ', '', l)))
    return out


def sentences(src):
    out = []
    for n, l in src:
        for s in re.split(r'(?<=[.!?؟])\s+', l):
            if sum(ch.isalpha() for ch in s) >= 3:
                out.append((n, s.strip()))
    return out


def norm(s):
    s = unicodedata.normalize('NFKD', s)
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    s = s.replace('صلى الله عليه وسلم', 'ﷺ').replace("(Allah’s prayers and peace be upon him)", '(pbuh)')
    s = re.sub(r'[^\w\sﷺ%]', ' ', s)
    s = re.sub(r'\b\d+\b', ' ', s)
    return re.sub(r'\s+', ' ', s).strip().lower()


def wdiff(a, b):
    out = []
    for tok in difflib.ndiff(a.split(), b.split()):
        if tok[0] in '+-':
            out.append(tok[0] + tok[2:])
    return ' '.join(out)


def compare(lang):
    sheet = sentences(lines(f'{lang}_sheet.txt', True))
    site = sentences(lines(f'{lang}.txt', False))
    site_n = [(n, s, norm(s)) for n, s in site]
    used, report, harakat_only = set(), [], 0
    for rn, s in sheet:
        ns = norm(s)
        best, bi = 0, -1
        for k, (_, _, nt) in enumerate(site_n):
            sm = difflib.SequenceMatcher(None, ns, nt, autojunk=False)
            if sm.real_quick_ratio() < best or sm.quick_ratio() < best:
                continue
            r = sm.ratio()
            if r > best:
                best, bi = r, k
        if best >= 0.6:
            used.add(bi)
            ln, t, nt = site_n[bi]
            if ns == nt:
                if s != t:
                    harakat_only += 1
                continue
            report.append(f'[{lang}] sheet row {rn} / site line {ln}\n  sheet: {s}\n  site : {t}\n  diff : {wdiff(nt, ns)}')
        else:
            report.append(f'[{lang}] ONLY IN SHEET row {rn}: {s}')
    for k, (ln, t, nt) in enumerate(site_n):
        if k not in used and not any(nt in norm(s) for _, s in sheet):
            report.append(f'[{lang}] ONLY ON SITE line {ln}: {t}')
    return report, harakat_only


def main():
    out = ['Spreadsheet vs official site — wording differences (harakat, punctuation, list markers and',
           'spacing ignored; "diff" shows -site words / +spreadsheet words). Generated by compare_sheet_site.py.', '']
    for lang in ('ar', 'en'):
        rep, h = compare(lang)
        out.append(f'===== {lang}: {len(rep)} differing sentences; {h} more sentences differ only in harakat/punctuation')
        out.extend(rep)
        out.append('')
    with open(os.path.join(HERE, 'sheet_vs_site.txt'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(out) + '\n')
    print('\n'.join(l for l in out if l.startswith('=====')))


if __name__ == '__main__':
    main()
