"""Unit 2 — ربي ونبيي وكتابي (LRN-09). Line numbers: ar/en = spreadsheet rows, tl = site lines."""
from build import S, J, D, Q, X, C, O, L, T, choose, order, match

TITLE = 'repeats the section title (shown as the lesson title)'
NAME = 'divine name written in Latin letters (transliteration); the English name and its meaning follow'

u2l1 = L(
    'u2-l1', T('ربي الله', 'My Lord Is Allah', 'Ang Aking Panginoon ay si Allah'),
    {'site_section': 'ربي الله (until «من أسمائه الحسنى»)', 'steps': None, 'page_ar': '13–14'},
    {'ar': [(15, 18)], 'en': [(15, 18)], 'tl': [(3, 7)]},
    [
        C('text', 'my lord', ar=[S(15, None, 'قال تعالى:')], en=[S(15, None, 'Allah Almighty says:')],
          tl=[S(3, None, 'Sinabi ng Allah:')], q=(2, 21, 21)),
        C('text', 'my lord', ar=[S(15, 'قال تعالى: ﴿هُو', 'قال تعالى:')], en=[S(15, 'He also says: {He', 'He also says:')],
          tl=[S(4, None, 'At sinabi pa ng Allah:')], q=(59, 22, 22)),
        C('text', 'my lord', ar=[S(15, 'قال تعالى: (ليس', 'قال تعالى:')], en=[S(15, 'He also says: There', 'He also says:')],
          tl=[Q(5)], q=(42, 11, 11)),
        C('text', 'my lord', ar=[16, 17], en=[16, 17], tl=[6]),
        C('text', 'my lord', ar=[18], en=[18], tl=[7]),
    ],
    [
        O(T('يعرف أن الله ربه ورب كل شيء: المالك الخالق الرازق المدبّر',
            'Knows that Allah is his Lord and the Lord of all things: the Possessor, the Creator, the Provider, the Disposer',
            'Alam na si Allah ang kanyang Panginoon at Panginoon ng lahat ng bagay: ang Tagapaglikha, Tagapagtustos at Tagapangasiwa'),
          [4], key=True),
        O(T('يعرف أن الله وحده المستحق للعبادة، لا ربّ غيره ولا إله سواه',
            'Knows that Allah alone is worthy of worship, with no lord or god other than Him',
            'Alam na si Allah lamang ang karapat-dapat sambahin, walang ibang Panginoon at Diyos maliban sa Kanya'),
          [4, 1, 2], key=True),
        O(T('يعرف أن لله الأسماء الحسنى والصفات العلا، وأنه ليس كمثله شيء',
            'Knows that Allah has the excellent names and sublime attributes, and that nothing is like Him',
            'Alam na si Allah ay may magagandang Pangalan at mararangal na katangian, at walang katulad Niya'), [5, 3]),
    ],
    [
        match([1, 2, 3], [4, 5], T('صِل كل عبارة بما يتمّ معناها', 'Match each statement with what completes its meaning', 'Itugma ang bawat pahayag sa kukumpleto ng kahulugan nito'),
              [(T('الله هو ربي ورب كل شيء', 'Allah is my Lord and the Lord of all things',
                  'Si Allah ang aking Panginoon at Panginoon ng lahat ng bagay'),
                T('المالك، الخالق، الرازق، المدبّر كل شيء', 'the Possessor, the Creator, the Provider, the Disposer of everything',
                  'ang Tagapaglikha, ang Tagapagtustos, at ang Tagapangasiwa ng lahat ng bagay')),
               (T('وهو المستحق وحده العبادة', 'He alone is worthy of being worshiped',
                  'Siya lamang ang karapat-dapat na pag-ukulan ng pagsamba'),
                T('لا ربّ غيره ولا إله سواه', 'there is no lord or god other than Him',
                  'walang ibang Panginoon at walang ibang Diyos maliban sa Kanya')),
               (T('له الأسماء الحسنى والصفات العلا', 'To Him belong the excellent names and sublime attributes',
                  'Siya ay may magagandang Pangalan at mararangal na katangian'),
                T('بلغت الغاية في الكمال والحُسن', 'at the pinnacle of perfection and beauty',
                  'na naabot ang sukdulan ng pagiging perpekto at kagandahan'))]),
        choose([3], [5], T('مَن أثبت لله الأسماء الحسنى والصفات العلا؟', 'Who established the excellent names and sublime attributes for Allah?', 'Sino ang naglarawan kay Allah ng magagandang Pangalan at mararangal na katangian?'),
               [T('أثبتها الله لنفسه، وأثبتها له نبيه ﷺ', 'Allah established them for Himself, and the Prophet established them for Him',
                  'Inilarawan Niya ito sa Kanyang sarili, at inilarawan ito sa Kanya ng Kanyang Propeta'),
                T('اخترعها الناس من عند أنفسهم', 'People made them up themselves', 'Inimbento ito ng mga tao mula sa kanilang sarili'), T('الملائكة وحدهم', 'The angels alone', 'Ang mga anghel lamang')]),
        choose([2], [4, 1, 2], T('ما معنى أن الله هو المستحق وحده العبادة؟', 'What does it mean that Allah alone is worthy of worship?', 'Ano ang kahulugan na si Allah lamang ang karapat-dapat sambahin?'), [T('لا ربّ غيره ولا إله سواه', 'There is no lord or god other than Him', 'Walang ibang Panginoon at walang ibang Diyos maliban sa Kanya'), T('يُعبد الله ويُعبد معه غيره', 'Allah is worshipped along with others', 'Sinasamba si Allah kasama ng iba'), T('العبادة لكل من نحبّه', 'Worship is for anyone we love', 'Ang pagsamba ay para sa sinumang mahal natin')]),
        choose([1], [4, 1], T('أيّ هذه من معاني أن الله رب كل شيء؟', 'Which of these is part of Allah being the Lord of all things?', 'Alin dito ang bahagi ng pagiging Panginoon ni Allah ng lahat ng bagay?'), [T('أنه المالك، الخالق، الرازق، المدبّر كل شيء', 'He is the Possessor, the Creator, the Provider and the Disposer of everything', 'Siya ang Tagapagmay-ari, ang Tagapaglikha, ang Tagapagtustos at ang Tagapangasiwa ng lahat ng bagay'), T('أنه خلق الأشياء ثم تركها بلا تدبير', 'He created things and then left them unmanaged', 'Nilikha Niya ang mga bagay at pinabayaan'), T('أن لكل شيء ربًّا غيره', 'Each thing has a lord other than Him', 'May ibang panginoon ang bawat bagay')]),
        choose([3], [5, 3], T('هل يشبه اللهَ شيءٌ من خلقه؟', 'Is anything in creation like Allah?', 'May katulad ba si Allah sa Kanyang mga nilikha?'),
               [T('ليس كمثله شيء، وهو السميع البصير', 'There is nothing like unto Him, and He is the All-Hearing, the All-Seeing',
                  'Wala Siyang kahalintulad na bagay; Siya ang Labis na Nakakarinig at Labis na Nakakakita'),
                T('له مثيل من خلقه', 'Something in His creation is like Him', 'May katulad Siya sa Kanyang mga nilikha'), T('يشبه الإنسانَ في صفاته', 'He resembles people in His attributes', 'Kahawig Niya ang tao sa Kanyang mga katangian')]),
    ],
    notes='Section «ربي الله» up to the list of names. Three verses are shown from the Quran database '
          '(2:21, 59:22, 42:11). The Filipino page gives verse 42:11 with no words before it, so card 3 has '
          'an empty Filipino text and shows only the verse.',
)

u2l2 = L(
    'u2-l2', T('من أسماء ربي الحسنى', 'Some of My Lord’s Beautiful Names', 'Ilan sa Magagandang Pangalan ng Aking Panginoon'),
    {'site_section': 'ربي الله › «من أسمائه الحسنى» and the 12 name tabs', 'steps': None, 'page_ar': '14–18'},
    {'ar': [(19, 33)], 'en': [(19, 33)], 'tl': [(8, 8), (11, 34)]},
    [
        C('text', 'names 1-4', ar=[19, 20, 21, 22, 23, 24],
          en=[19, S(21, drop=[D('Ar-Razzāq: ', NAME)]), S(22, drop=[D('Ar-Rahmān: ', NAME)]),
              S(23, drop=[D('Al-Qadeer: ', NAME)]), S(24, drop=[D('Al-Malik: ', NAME)])],
          tl=[12, 14, 16, 18]),
        C('text', 'names 5-8', ar=[25, 26, 27, 28],
          en=[S(25, drop=[D('As-Samee‘: ', NAME)]), S(26, drop=[D('As-Salām: ', NAME)]),
              S(27, drop=[D('Al-Baseer: ', NAME)]), S(28, drop=[D('Al-Wakeel: ', NAME)])],
          tl=[20, 22, 24, 26]),
        C('text', 'names 9-12', ar=[29, 30, 31, 32],
          en=[S(29, drop=[D('Al-Khāliq: ', NAME)]), S(30, drop=[D('Al-Lateef: ', NAME)]),
              S(31, drop=[D('Al-Kāfi: ', NAME)]), S(32, drop=[D('Al-Ghafoor: ', NAME)])],
          tl=[28, 30, 32, 34]),
        C('text', 'reflection', ar=[33], en=[33], tl=[8]),
    ],
    [
        O(T('يعرف معاني: الرزّاق، الرحمن، القدير، الملك', 'Knows the meanings of the Provider, the Most Merciful, the All-Powerful and the King',
            'Alam ang kahulugan ng Tagapanustos, Pinaka Maawain, Makapangyarihan at Hari'), [1], key=True),
        O(T('يعرف معاني: السميع، السلام، البصير، الوكيل', 'Knows the meanings of the All-Hearing, the Perfect, the All-Seeing and the Trustee',
            'Alam ang kahulugan ng Nakakarinig, Ligtas o Payapa, Nakakakita at Tagapagkupkop'), [2], key=True),
        O(T('يعرف معاني: الخالق، اللطيف، الكافي، الغفور', 'Knows the meanings of the Creator, the Subtle and Kind, the Sufficient and the All-Forgiving',
            'Alam ang kahulugan ng Tagapaglikha, Banayad at Mabait, Sapat at Nagpapatawad'), [3]),
        O(T('يتفكّر في خلق الله ولطفه بمخلوقاته كما وصف الدرس', 'Reflects on Allah’s creation and His kindness to His creatures, as the lesson describes',
            'Nagninilay sa nilikha ng Allah at sa Kanyang kabaitan sa mga ito, ayon sa aralin'), [4]),
    ],
    [
        match([1], [1], T('صِل كل اسم بمعناه', 'Match each name with its meaning', 'Itugma ang bawat pangalan sa kahulugan nito'),
              [(T('الرزّاق', 'The Provider', 'Ang Tagapanustos'),
                T('المتكفّل بأرزاق العباد التي بها قوام قلوبهم وأبدانهم', 'provides His creation with the sustenance necessary for their souls and bodies',
                  'sa mga biyaya ng mga alipin, na siyang lakas ng kanilang mga puso at katawan')),
               (T('الرحمن', 'The Most Merciful', 'Ang Pinaka Maawain'),
                T('ذو الرحمة الواسعة العظيمة التي وسعت كل شيء', 'Whose mercy encompasses everything',
                  'ang Kanyang Awa ay saklaw ang lahat ng bagay')),
               (T('القدير', 'The All-Powerful', 'Ang ganap na Makapangyarihan'),
                T('ذو القدرة الكاملة الذي لا يعتريه عجز ولا فتور', 'Who experiences neither inability nor languish',
                  'hindi nakakaranas ng pagkapagod o kawalan ng kakayahan')),
               (T('الملك', 'The King and Sovereign', 'Ang Kataas-taasang Hari'),
                T('المالك لجميع الأشياء المتصرف فيها', 'Who owns and directs everything', 'Tagapangasiwa ng lahat ng mga bagay'))]),
        choose([1], [1], T('أيّ اسم معناه: ذو القدرة الكاملة الذي لا يعتريه عجز ولا فتور؟', 'Which name means: the One who never experiences inability or weariness?', 'Aling pangalan ang nangangahulugang: hindi nakakaranas ng pagkapagod o kawalan ng kakayahan?'), [T('القدير', 'The All-Powerful', 'Ang ganap na Makapangyarihan'), T('الرزّاق', 'The Provider', 'Ang Tagapanustos'), T('الملك', 'The King and Sovereign', 'Ang Kataas-taasang Hari')]),
        match([2], [2], T('صِل كل اسم بمعناه', 'Match each name with its meaning', 'Itugma ang bawat pangalan sa kahulugan nito'),
              [(T('السميع', 'The All-Hearing', 'Ang Nakakarinig'),
                T('الذي يدرك جميع المسموعات سرّها وجهرها', 'hears every heard thing, the secret thereof and the revealed',
                  'nakakaalam ng lahat ng binibigkas, lantaran man o palihim')),
               (T('السلام', 'The Perfect', 'Ang Ligtas o Payapa'),
                T('السالم من كل نقص وآفة وعيب', 'free of every deficiency and defect', 'sa lahat ng kakulangan, pagkababa at kapintasan')),
               (T('البصير', 'The All-Seeing', 'Ang ganap na Nakakakita'),
                T('الذي أحاط بصره بكل شيء وإن دقّ وصغر', 'Whose sight encompasses everything, however minute',
                  'ng lahat, ito man ay malaki o maliit')),
               (T('الوكيل', 'The Trustee', 'Ang Ganap na Tagapagkupkop'),
                T('الكفيل بأرزاق خلقه، والقائم عليهم بمصالحهم', 'guarantees provision to His creation and manages their affairs',
                  'Tagapangalaga ng mga biyaya ng mga nilikha at Tagapangasiwa ng Kanyang mga alipin'))]),
        choose([2], [2], T('أيّ اسم معناه: الذي أحاط بصره بكل شيء وإن دقّ وصغر؟', 'Which name means: the One whose sight encompasses everything, however small?', 'Aling pangalan ang nangangahulugang: nakikita ang lahat ng bagay, malaki man o maliit?'), [T('البصير', 'The All-Seeing', 'Ang ganap na Nakakakita'), T('السميع', 'The All-Hearing', 'Ang Nakakarinig'), T('الوكيل', 'The Trustee', 'Ang Ganap na Tagapagkupkop')]),
        match([3], [3], T('صِل كل اسم بمعناه', 'Match each name with its meaning', 'Itugma ang bawat pangalan sa kahulugan nito'),
              [(T('الخالق', 'The Creator', 'Ang Tagapaglikha'),
                T('موجد الأشياء ومبدعها على غير مثال سابق', 'creates things and brings them into existence in an unprecedented manner',
                  'ng lahat ng bagay, nang walang pinagbasihang mga bagay na nauna')),
               (T('اللطيف', 'The Subtle and Kind', 'Ang Banayad at ang Mabait'),
                T('الذي يكرم عباده ويرحمهم ويعطيهم سؤلهم', 'honors His servants, shows mercy to them and responds to their supplications',
                  'pinarangalan ang Kanyang mga lingkod at tinatanggap ang kanilang mga pagsusumamo')),
               (T('الكافي', 'The Sufficient', 'Ang Sapat'),
                T('الذي يكفي عباده جميع ما يحتاجون إليه', 'provides His servants with all their needs',
                  'nagbibigay sa Kanyang mga alipin ng lahat ng kanilang mga pangangailangan')),
               (T('الغفور', 'The All-Forgiving', 'Ang Nagpapatawad'),
                T('الذي يقي عباده شرّ ذنوبهم ولا يعاقبهم عليها', 'protects His servants from the evil of their sins and spares them the punishment',
                  'sa mga kasalanan ng Kanyang mga alipin at hindi na sila paparusahan'))]),
        choose([3], [3], T('أيّ اسم معناه: الذي يكفي عباده جميع ما يحتاجون إليه؟', 'Which name means: the One who provides His servants with all they need?', 'Aling pangalan ang nangangahulugang: nagbibigay sa Kanyang mga alipin ng lahat ng kanilang pangangailangan?'), [T('الكافي', 'The Sufficient', 'Ang Sapat'), T('الخالق', 'The Creator', 'Ang Tagapaglikha'), T('اللطيف', 'The Subtle and Kind', 'Ang Banayad at ang Mabait')]),
        choose([4], [4], T('ماذا يفعل المسلم حين يرى عناية المخلوقات بصغارها؟', 'What does a Muslim do when he sees creatures caring for their young?', 'Ano ang ginagawa ng Muslim kapag nakita niya ang pag-aalaga ng mga nilalang sa kanilang mga anak?'),
               [T('أن يتفكر في عجيب خلق الله وتيسيره', 'To reflect upon Allah’s wonderful creation and how He makes things easy',
                  'Magnilay-nilay sa kamangha-manghang nilikha ng Allah at sa Kanyang pagpapagaan'),
                T('أن يمرّ بالمخلوقات دون تفكر', 'To pass by the creatures without reflecting', 'Lampasan ang mga nilikha nang hindi nagninilay'), T('أن يظن أن ذلك حدث مصادفة', 'To think it happened by chance', 'Isipin na nangyari ito nang nagkataon lamang')]),
        choose([4], [4], T('مَن هيّأ للمخلوقات الضعيفة ما يعينها ويصلح حالها؟',
                           'Who provided the weak creatures with what helps them?',
                           'Sino ang nagbigay sa mahihinang nilikha ng makakatulong sa kanila?'),
               [T('الله، الخالق لها واللطيف بها', 'Allah, Who created them and showed kindness to them',
                  'Si Allah, na naglikha sa mga ito at naging banayad sa mga ito'),
                T('المخلوقات نفسها دون الله', 'The creatures themselves, without Allah', 'Ang mga nilikha mismo, nang wala ang Allah'), T('الإنسان وحده', 'People alone', 'Ang tao lamang')]),
    ],
    xdrops=[X('en', 20, reason='list of the names written in Latin letters (transliteration) with English names in brackets; '
                              'the English names are given with their meanings in the cards', card=1)],
    notes='The list of the twelve names and their meanings. The site splits name and meaning into tabs; '
          'the spreadsheet (and printed book) give "name: meaning", used here. English: every transliterated '
          'name (e.g. "Ar-Razzāq:") was dropped; the English name opening each meaning stays. Filipino: the '
          'page has no list; the tab labels are transliterated names (not used); each card shows the Filipino '
          'meanings, which begin with the Filipino name. The Filipino reflection paragraph (card 4) differs in '
          'detail from the Arabic (creatures caring for themselves rather than for their young); exercises '
          'use only what the three languages share. Arabic «الخالق»: the spreadsheet and printed book differ '
          '(مبدعها / مخترعها) — see README.',
)

u2l3 = L(
    'u2-l3', T('نبيي محمد ﷺ', 'My Prophet Is Muhammad ﷺ', 'Ang Aking Propeta ay si Muhammad ﷺ'),
    {'site_section': 'نبيّي محمد ﷺ', 'steps': None, 'page_ar': '20–22'},
    {'ar': [(34, 41)], 'en': [(34, 41)], 'tl': [(49, 63)]},
    [
        C('text', 'my prophet', ar=[S(35, None, 'قال تعالى:')], en=[S(35, None, 'Allah Almighty says:')],
          tl=[S(49, None, 'Sinabi ng Allah:')], q=(9, 128, 128)),
        C('text', 'my prophet', ar=[S(35, 'قال تعالى: ﴿و', 'قال تعالى:')], en=[S(35, 'Allah Almighty says: {And', 'Allah Almighty says:')],
          tl=[S(50, None, 'At Kanyang pang sinabi:')], q=(21, 107, 107)),
        C('text', 'my prophet', ar=[36, 37, 38, 39], en=[36, 37, 38, 39], tl=[51, 52]),
        C('text', 'his traits', ar=[40, 41], en=[40, 41], tl=[53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]),
    ],
    [
        O(T('يعرف أن محمدًا ﷺ خاتم الأنبياء والمرسلين، أرسله الله بالإسلام إلى الناس كافة',
            'Knows that Muhammad ﷺ is the final Prophet and Messenger, sent with Islam to all humankind',
            'Alam na si Muhammad ﷺ ang panghuling Propeta at Sugo, na ipinadala dala ang Islam para sa buong sangkatauhan'),
          [3, 1, 2], key=True),
        O(T('يعرف أن أعظم الخير الذي دلّ عليه التوحيد، وأعظم الشر الذي نهى عنه الشرك',
            'Knows that the greatest good he guided to is monotheism and the worst evil he warned against is polytheism',
            'Alam na ang pinakamainam na kabutihan na itinuro niya ay ang Tawheed at ang pinakamasamang kasamaan ay ang pagtatambal'), [3]),
        O(T('يذكر من صفات النبي ﷺ', 'Names some of the traits of the Prophet ﷺ', 'Nasasabi ang ilan sa mga katangian ng Propeta ﷺ'),
          [4], key=True),
    ],
    [
        choose([1], [3], T('محمد ﷺ هو:', 'Muhammad ﷺ is:', 'Si Muhammad ﷺ ay:'),
               [T('خاتم الأنبياء والمرسلين', 'the final Prophet and Messenger', 'ang panghuling Propeta at Sugo'),
                T('أول الأنبياء', 'the first of the prophets', 'ang unang Propeta'), T('ملَك من الملائكة', 'An angel', 'Isang anghel')]),
        choose([1], [3, 1, 2], T('إلى مَن أرسله الله تعالى بدين الإسلام؟', 'To whom did Allah send him with the religion of Islam?',
                                 'Para kanino siya ipinadala ng Allah dala ang relihiyong Islam?'),
               [T('إلى الناس كافة', 'To all humankind', 'Para sa buong sangkatauhan'),
                T('إلى قومه فقط', 'To his own people only', 'Para sa kanyang angkan lamang'), T('إلى أهل مكة وحدهم', 'To the people of Makkah only', 'Sa mga tao ng Makkah lamang')]),
        match([2], [3], T('صِل كلًّا منهما بأعظمه', 'Match each with the greatest of it', 'Itugma ang bawat isa sa pinakadakila nito'),
              [(T('الخير', 'All that is good', 'Ang daan ng kabutihan'),
                T('وأعظمه التوحيد', 'the greatest of which is monotheism', 'ang pinakamainam dito ay ang Tawheed')),
               (T('الشر', 'All that is evil', 'Ang daan ng kasamaan'),
                T('وأعظمه الشرك', 'the worst of which is polytheism', 'ang pinakamasama dito ay ang pagtatambal'))]),
        choose([2], [3], T('أعظم الخير الذي دلّ عليه النبي ﷺ:', 'The greatest good that the Prophet ﷺ guided people to:',
                           'Ang pinakamainam na kabutihan na itinuro ng Propeta ﷺ:'),
               [T('التوحيد', 'Monotheism', 'Ang Tawheed o kaisahan ng Allah'), T('الشرك', 'Polytheism', 'Ang pagtatambal'), T('كثرة المال', 'Having much wealth', 'Pagkakaroon ng maraming kayamanan')]),
        choose([3], [4], T('أيّ مجموعة كلها من صفاته ﷺ؟', 'Which group lists only his qualities (peace be upon him)?', 'Aling grupo ang pawang mga katangian niya (pagpalain siya ni Allah)?'),
               [T('الصدق، والرحمة، والحلم', 'Honesty, mercy, forbearance', 'Makatotohanan, mahabagin, maunawain'),
                T('الناس، والخير، والأنبياء', 'People, good, prophets', 'Sangkatauhan, kabutihan, propeta'), T('الغضب، والكِبر، والقسوة', 'Anger, arrogance and harshness', 'Galit, kayabangan at kalupitan')]),
        choose([3], [4], T('وأيّ مجموعة أخرى كلها من صفاته ﷺ؟', 'And which other group lists only his traits ﷺ?',
                           'At aling iba pang grupo ang naglalaman lamang ng kanyang mga katangian ﷺ?'),
               [T('التواضع، والعفو، والعدل', 'Modesty, forgiveness, fairness', 'Mapagkumbaba, mapagpatawad, makatarungan'),
                T('الإسلام، والتوحيد، والرسالة', 'Islam, monotheism, the message', 'Islam, Tawheed, mensahe'), T('البخل، والجبن، والكذب', 'Stinginess, cowardice and lying', 'Pagkakuripot, karuwagan at pagsisinungaling')]),
    ],
    xdrops=[X('ar', 34, reason=TITLE), X('en', 34, reason=TITLE)],
    notes='Section «نبيّي محمد ﷺ». The Filipino page does not translate two Arabic/English sentences (the duty to '
          'obey him, and the message of all prophets); card 3 therefore has more text in Arabic/English than in '
          'Filipino, and no exercise asks about those two sentences.',
)

u2l4 = L(
    'u2-l4', T('القرآن كلام ربي', 'The Qur’an Is the Word of My Lord', 'Ang Qur’an ay Salita ng Aking Panginoon'),
    {'site_section': 'القرآن كلام ربي', 'steps': None, 'page_ar': '24–25'},
    {'ar': [(43, 45)], 'en': [(43, 45)], 'tl': [(66, 68)]},
    [
        C('text', 'quran', ar=[S(43, None, 'قال تعالى:')], en=[S(43, None, 'Allah Almighty says:')],
          tl=[S(66, None, 'Sinabi ng Allah:')], q=(4, 174, 174)),
        C('text', 'quran', ar=[44], en=[44], tl=[67]),
        C('text', 'quran', ar=[45], en=[45], tl=[68]),
    ],
    [
        O(T('يعرف أن القرآن كلام الله أنزله على نبيه محمد ﷺ', 'Knows that the Qur’an is the word of Allah, revealed to His Prophet Muhammad ﷺ',
            'Alam na ang Qur’an ay salita ng Allah na ipinahayag kay Propeta Muhammad ﷺ'), [2, 1], key=True),
        O(T('يعرف لماذا أنزل الله القرآن', 'Knows why Allah revealed the Qur’an', 'Alam kung bakit ipinahayag ng Allah ang Qur’an'), [2]),
        O(T('يعرف فضل قراءة القرآن والعمل بهديه', 'Knows the reward of reading the Qur’an and acting upon its guidance',
            'Alam ang gantimpala ng pagbasa ng Qur’an at pagsunod sa patnubay nito'), [3], key=True),
    ],
    [
        choose([1], [2, 1], T('القرآن الكريم هو:', 'The Noble Qur’an is:', 'Ang Maluwalhating Qur’an ay:'),
               [T('كلام الله تعالى', 'the word of Allah Almighty', 'salita ng Allah'),
                T('كلام النبي ﷺ', 'the word of the Prophet ﷺ', 'salita ng Propeta ﷺ'),
                T('كلام الناس', 'the word of people', 'salita ng mga tao')]),
        match([1, 2], [2], T('صِل كل جزء بما يتمّ معناه', 'Match each part with what completes its meaning', 'Itugma ang bawat bahagi sa kukumpleto ng kahulugan nito'),
              [(T('أنزله الله', 'Allah revealed it', 'Ipinahayag ito ng Allah'),
                T('على نبيه محمد ﷺ', 'to His Prophet Muhammad (pbuh)', 'kay Propeta Muhammad ﷺ')),
               (T('ليخرج الناس', 'to bring mankind', 'upang hanguin ang mga tao'),
                T('من الظلمات إلى النور', 'out of darknesses into the light', 'mula sa kadiliman tungo sa liwanag')),
               (T('ويهديهم', 'and guide them', 'at gabayan sila'),
                T('إلى الصراط المستقيم', 'to the straight path', 'sa matuwid na landas'))]),
        choose([2], [2], T('أنزل الله القرآن ليخرج الناس:', 'Allah revealed the Qur’an to bring mankind:',
                           'Ipinahayag ng Allah ang Qur’an upang hanguin ang mga tao:'),
               [T('من الظلمات إلى النور', 'out of darknesses into the light', 'mula sa kadiliman tungo sa liwanag'),
                T('من النور إلى الظلمات', 'out of the light into darknesses', 'mula sa liwanag tungo sa kadiliman'), T('ليشقّ عليهم في حياتهم', 'To make their lives hard', 'Upang pahirapan ang kanilang buhay')]),
        match([3], [3], T('صِل كل عمل بثمرته', 'Match each deed with its fruit', 'Itugma ang bawat gawa sa bunga nito'),
              [(T('من قرأه', 'Whoever reads it', 'Sinuman ang magbasa nito'),
                T('حصل له أجر عظيم', 'earns a great reward', 'ay makakatamo ng dakilang gantimpala')),
               (T('من عمل بهديه', 'Whoever acts upon its guidance', 'Sinuman ang gawing patnubay ang Qur’an'),
                T('سلك الطريق القويم', 'is on the true path', 'ay tinahak ang matuwid na landas'))]),
        choose([3], [3], T('ماذا يحصل لمن قرأ القرآن؟', 'What does the one who reads the Qur’an earn?',
                           'Ano ang makakamit ng sinumang magbasa ng Qur’an?'),
               [T('أجر عظيم', 'A great reward', 'Dakilang gantimpala'), T('الظلمات', 'Darknesses', 'Kadiliman'), T('لا شيء', 'Nothing', 'Wala')]),
    ],
    notes='Section «القرآن كلام ربي». The verse (An-Nisa 4:174) is shown from the Quran database (LRN-09 rule 2 example).',
)

LESSONS = [u2l1, u2l2, u2l3, u2l4]
