"""Unit 1 — دليل اليوم الأول (LRN-01). Line numbers: ar/en = spreadsheet rows, tl = site lines."""
from build import S, J, D, Q, X, C, O, L, T, LBL, choose, order, match

TR = 'transliteration'
MEANING = ('English/Filipino meaning of a dhikr whose Latin transliteration was dropped; dropped with it '
           'so the learner is not led to say a translation in prayer (adhkar are learned by listening, '
           'rules 1.4; LRN-01 rule 4)')
TITLE = 'repeats the section title (shown as the lesson title)'

u1l1 = L(
    'u1-l1', T('أشهد: معنى الشهادتين', 'I Bear Witness: The Meaning of the Two Testimonies',
               'Ako ay Sumasaksi: Ang Kahulugan ng Dalawang Pagsaksi'),
    {'site_section': 'أتعرف على أركان الإسلام › الركن الأول (tab5_1)', 'steps': None, 'page_ar': '30–31'},
    {'ar': [(50, 53)], 'en': [(50, 53)], 'tl': [(77, 82)]},
    [
        C('text', 'pillar 1', ar=[50, S(51, None, 'قال تعالى:')], en=[50, S(51, None, 'Allah Almighty says:')],
          tl=[77, 78, S(79, None, 'Sinabi ng Allah:')], q=(47, 19, 19)),
        C('text', 'pillar 1', ar=[S(51, 'وقال تعالى:', 'وقال تعالى:')], en=[S(51, 'He also says:', 'He also says:')],
          tl=[S(80, None, 'Sinabi pa ng Allah:')], q=(9, 128, 128)),
        C('text', 'pillar 1', ar=[52], en=[52], tl=[S(81, drop=[' ng ‘’la ilaha illa Allah’’'])]),
        C('text', 'pillar 1', ar=[53], en=[53], tl=[82]),
    ],
    [
        O(T('يعرف معنى شهادة أن لا إله إلا الله: لا معبود حق إلا الله',
            'Knows the meaning of the testimony that there is no god but Allah: there is no deity worthy of worship except Allah',
            'Alam ang kahulugan ng pagsaksi na walang diyos maliban sa Allah: walang ibang diyos na karapat-dapat sambahin maliban sa Allah'),
          [3], key=True),
        O(T('يعرف معنى شهادة أن محمدًا رسول الله',
            'Knows the meaning of the testimony that Muhammad is the Messenger of Allah',
            'Alam ang kahulugan ng pagsaksi na si Muhammad ay Sugo ng Allah'), [4, 2], key=True),
        O(T('يعرف أن الشهادتين هما الركن الأول من أركان الإسلام',
            'Knows that the two testimonies are the first pillar of Islam',
            'Alam na ang dalawang pagsaksi ang unang haligi ng Islam'), [1]),
    ],
    [
        choose([1], [3], T('ما معنى شهادة أن لا إله إلا الله؟',
                           'What does the testimony "there is no god but Allah" mean?',
                           'Ano ang kahulugan ng pagsaksi na walang diyos maliban sa Allah?'),
               [T('لا معبودَ حقٌّ إلا الله', 'There is no deity worthy of worship except Allah',
                  'Walang ibang diyos na karapat-dapat sambahin maliban sa Allah'),
                T('طاعة النبي ﷺ فيما أمر', 'Obeying the orders of the Prophet ﷺ', 'Ang pagsunod sa utos ng Propeta ﷺ'),
                T('أن محمدًا رسول الله', 'That Muhammad is the Messenger of Allah', 'Na si Muhammad ay Sugo ng Allah')]),
        choose([2], [4, 2], T('مما يدخل في معنى شهادة أن محمدًا رسول الله:',
                              'Which of these is part of the meaning of the testimony that Muhammad is the Messenger of Allah?',
                              'Alin dito ang bahagi ng kahulugan ng pagsaksi na si Muhammad ay Sugo ng Allah?'),
               [T('طاعته فيما أمر، وتصديقه فيما أخبر', 'Obeying his orders and believing what he related',
                  'Ang pagsunod sa kanyang utos at paniniwala sa kanyang ibinalita'),
                T('أن يُعبد الله بغير ما شرع', 'Worshipping Allah in a way other than what he instructed',
                  'Ang pagsamba sa Allah sa paraang hindi niya itinuro'),
                T('فعل ما نهى عنه وزجر', 'Doing what he forbade and warned against',
                  'Ang paggawa ng kanyang ipinagbawal')]),
        match([1, 2], [3, 4], T('صِل كل شهادة بمعناها', 'Match each testimony with its meaning',
                                'Itugma ang bawat pagsaksi sa kahulugan nito'),
              [(T('شهادة أن لا إله إلا الله', 'The testimony that there is no god but Allah',
                  'Ang pagsaksi na walang diyos maliban sa Allah'),
                T('لا معبود حق إلا الله', 'There is no deity worthy of worship except Allah',
                  'Walang ibang diyos na karapat-dapat sambahin maliban sa Allah')),
               (T('شهادة أن محمدًا رسول الله', 'The testimony that Muhammad is the Messenger of Allah',
                  'Ang pagsaksi na si Muhammad ay Sugo ng Allah'),
                T('طاعته فيما أمر، وتصديقه فيما أخبر، واجتناب ما نهى عنه، وألا يُعبد الله إلا بما شرع',
                  'Obeying his orders, believing what he related, avoiding what he forbade, and worshipping Allah only in the manner he instructed',
                  'Pagsunod sa kanyang utos, paniniwala sa kanyang ibinalita, pag-iwas sa kanyang ipinagbawal, at pagsamba sa Allah alinsunod sa kanyang itinuro'))]),
        choose([3], [1], T('الشهادتان هما:', 'The two testimonies are:', 'Ang dalawang pagsaksi ay:'),
               [T('الركن الأول من أركان الإسلام', 'The first pillar of Islam', 'Ang unang haligi ng Islam'),
                T('الركن الثاني من أركان الإسلام', 'The second pillar of Islam', 'Ang ikalawang haligi ng Islam'),
                T('ليستا من أركان الإسلام', 'Not one of the pillars of Islam', 'Hindi kabilang sa mga haligi ng Islam')]),
        choose([3, 1], [1, 2], T('بماذا يشهد المسلم في الركن الأول؟', 'In the first pillar, what does the Muslim bear witness to?',
                                 'Sa unang haligi, ano ang pinapatotohanan ng isang Muslim?'),
               [T('أن لا إله إلا الله، وأن محمدًا رسول الله', 'That there is no god except Allah, and that Muhammad is the Messenger of Allah',
                  'Na walang diyos na karapat-dapat sambahin maliban sa Allah, at si Muhammad ay Sugo ng Allah'),
                T('أن محمدًا رسول الله فقط', 'Only that Muhammad is the Messenger of Allah',
                  'Ang pagiging Sugo ni Muhammad lamang'),
                T('أن لا إله إلا الله فقط', 'Only that there is no god except Allah',
                  'Na walang diyos maliban sa Allah, iyon lamang')]),
    ],
    notes='Section «الركن الأول» of «أتعرف على أركان الإسلام». The two verses are shown from the Quran '
          'database (Muhammad 47:19, At-Tawbah 9:128). In Filipino the transliterated words of the testimony '
          'were dropped from card 3; the meaning sentence stays.',
)

u1l2 = L(
    'u1-l2', T('قبل الوضوء: ما يجب له الوضوء، والماء الطهور', 'Before Wudu: What Requires Wudu, and Purifying Water',
               'Bago ang Wudhu: Kailan Kailangan ang Wudhu, at ang Malinis na Tubig'),
    {'site_section': 'أتعلم الوضوء (section intro, before the steps)', 'steps': None, 'page_ar': '60–62'},
    {'ar': [(116, 123)], 'en': [(116, 123)], 'tl': [(191, 204)]},
    [
        C('text', 'wudu intro', ar=[S(116, None, 'قال تعالى:')], en=[S(116, None, 'Allah Almighty says:')],
          tl=[S(191, None, 'Sinabi ng Allah:')], q=(2, 222, 222)),
        C('text', 'wudu intro', ar=[S(116, 'قال ﷺ: (ت', 'والصلاة نور).')],
          en=[S(116, 'The Prophet (pbuh) said: “Perform', 'and prayer is light."')], tl=[192, 193]),
        C('text', 'wudu intro', ar=[S(116, 'وقال ﷺ: (من توضأ'), 117], en=[S(116, 'He (pbuh) also said'), 117],
          tl=[194, 195]),
        C('text', 'what requires wudu', ar=[118, 119, 120, 121], en=[118, 119, 120, 121],
          tl=[196, 197, J(198), 199, J(200), 201, J(202)]),
        C('text', 'purifying water', ar=[122, 123], en=[122, 123], tl=[203, 204]),
    ],
    [
        O(T('يذكر ما يجب له الوضوء: الصلاة، والطواف بالكعبة، ومسّ المصحف',
            'Names what wudu is required for: prayer, circling the Ka‘bah, and touching the Mus-haf',
            'Nasasabi kung kailan kailangan ang wudhu: sa Salah, sa pagtawaf sa Ka’bah, at sa paghawak ng Mushaf'), [4], key=True),
        O(T('يعرف الماء الطهور الذي يُتوضأ ويُغتسل به',
            'Recognises the purifying water used for wudu and ghusl',
            'Nakikilala ang malinis na tubig na ginagamit sa wudhu at paliligo'), [5], key=True),
        O(T('يعرف أن الله جعل الطهارة شرطًا لصحة الصلاة ومفتاحًا لها',
            'Knows that Allah made purification a condition for the validity of prayer and its key',
            'Alam na ginawa ng Allah ang paglilinis na kondisyon at susi ng Salah'), [1, 2, 3]),
    ],
    [
        choose([1], [4], T('الوضوء يجب للصلاة:', 'Wudu is required for prayer:', 'Kailangan ang wudhu sa Salah:'),
               [T('فرضًا كانت أو نافلة', 'whether mandatory or supererogatory (voluntary)', 'obligado man o sunnah'),
                T('الفريضة فقط', 'only the mandatory prayer', 'sa obligadong Salah lamang'),
                T('النافلة فقط', 'only the voluntary prayer', 'sa sunnah na Salah lamang')]),
        choose([1], [4], T('أكمل ما يجب له الوضوء كما في الدرس: الصلاة، والطواف بالكعبة، و…',
                           'Complete what wudu is required for, as in the lesson: prayer, circling the Ka‘bah, and …',
                           'Kumpletuhin kung kailan kailangan ang wudhu ayon sa aralin: Salah, pagtawaf sa Ka’bah, at …'),
               [T('مسّ المصحف', 'touching the Mus-haf (copy of the Qur’an)', 'paghawak ng Mushaf (Qur’an)'),
                T('لون الماء وطعمه', 'the colour and taste of water', 'ang kulay at lasa ng tubig'),
                T('الماء النازل من السماء', 'water that falls from the sky', 'tubig na nagmula sa langit')]),
        choose([2], [5], T('الماء الطهور هو كل ماء:', 'Purifying water is any water that:',
                           'Ang malinis na tubig ay lahat ng tubig na:'),
               [T('نزل من السماء أو نبع من الأرض، وبقي على أصل خلقته',
                  'falls from the sky or springs from the earth and stays in its original state',
                  'nagmula sa langit o lumabas mula sa lupa at nanatili sa orihinal na pagkalikha nito'),
                T('تغيّر لونه أو طعمه أو ريحه بشيء يسلب طهوريته',
                  'had its colour, taste or smell changed by something that takes away its purity',
                  'nabago ang kulay, lasa o amoy dahil sa bagay na nakakaalis ng pagkalinis nito')]),
        choose([2], [5], T('ما أوصاف الماء الثلاثة التي ذكرها الدرس؟',
                           'What are the three characteristics of water named in the lesson?',
                           'Ano ang tatlong katangian ng tubig na binanggit sa aralin?'),
               [T('اللون والطعم والريح', 'colour, taste and smell', 'kulay, lasa at amoy'),
                T('الصلاة والطواف ومسّ المصحف', 'prayer, circling the Ka‘bah and touching the Mus-haf',
                  'Salah, pagtawaf at paghawak ng Mushaf')]),
        choose([3], [2, 1], T('ما منزلة الطهارة من الصلاة كما في الدرس؟',
                              'What is purification to prayer, as the lesson says?',
                              'Ano ang kaugnayan ng paglilinis sa Salah ayon sa aralin?'),
               [T('شرط لصحة الصلاة، وهي مفتاحها', 'A condition for the validity of prayer, and its key',
                  'Ito ay kondisyon ng Salah at ito ang susi nito'),
                T('لا علاقة لها بالصلاة', 'It has nothing to do with prayer', 'Wala itong kinalaman sa Salah')]),
        match([3], [2, 3], T('صِل بداية كل قول للنبي ﷺ بتمامه كما في الدرس',
                             'Match the beginning of each saying of the Prophet ﷺ with its ending, as in the lesson',
                             'Itugma ang simula ng bawat sinabi ng Propeta ﷺ sa katapusan nito, ayon sa aralin'),
              [(T('الطهور', 'Purification', 'Ang kalinisan'),
                T('شطر الإيمان', 'is half of Imān', 'ay bahagi ng pananampalataya')),
               (T('والصلاة', 'And prayer', 'At ang Salah'), T('نور', 'is light', 'ay liwanag')),
               (T('من توضأ فأحسن الوضوء', 'He who performs wudu perfectly',
                  'Sinuman ang nagsagawa ng wudhu at ito ay kanyang pinabuti'),
                T('خرجت خطاياه من جسده', 'his sins come out from his body',
                  'maaalis ang kanyang mga kasalanan mula sa kanyang katawan'))]),
    ],
    notes='The PRD lists pp. 61–62; the section intro also includes the verse on p. 60 (Al-Baqarah 2:222), '
          'kept as card 1 so no sentence is lost. The spreadsheet and the Filipino page cite this verse as '
          '"2:22"; the quran field uses 2:222 (the Arabic site and the English text). Hadith are kept as the '
          'book quotes them (no hadith database id yet).',
)

u1l3 = L(
    'u1-l3', T('أتوضأ (1): الخطوات 1–4', 'I Perform Wudu (1): Steps 1–4', 'Ako ay Nagwu-wudhu (1): Mga Hakbang 1–4'),
    {'site_section': 'أتعلم الوضوء › tabs 1–4', 'steps': '1-4', 'page_ar': '63–66'},
    {'ar': [(124, 131)], 'en': [(124, 131)], 'tl': [(207, 220)]},
    [
        C('step', 'step 1', ar=[S(125, drop=[D('الخطوة 1: ', LBL)])], en=[S(125, drop=[D('Step 1: ', LBL)])], tl=[208]),
        C('step', 'step 2', ar=[S(126, drop=[D('الخطوة 2: ', LBL)])], en=[S(126, drop=[D('Step 2: ', LBL)])], tl=[211],
          img='tab3_2'),
        C('step', 'step 3', ar=[S(127, drop=[D('الخطوة 3: ', LBL)]), 128], en=[S(127, drop=[D('Step 3: ', LBL)]), 128],
          tl=[214, 215], img='tab3_3'),
        C('step', 'step 4', ar=[S(129, drop=[D('الخطوة 4: ', LBL)]), 130, 131],
          en=[S(129, drop=[D('Step 4: ', LBL)]), 130, 131], tl=[218, 219, 220], img='tab3_4'),
    ],
    [
        O(T('يعرف أن محل النية القلب', 'Knows that the place of the intention is the heart',
            'Alam na ang lugar ng intensyon ay ang puso'), [1], key=True),
        O(T('يرتّب خطوات الوضوء الأربع الأولى', 'Puts the first four steps of wudu in order',
            'Naisasaayos ang unang apat na hakbang ng wudhu'), [1, 2, 3, 4], key=True),
        O(T('يميّز المضمضة من الاستنشاق والاستنثار',
            'Tells rinsing the mouth apart from sniffing water into the nose and blowing it out',
            'Natutukoy ang pagkakaiba ng pagmumog, ng pagsinghot ng tubig at ng pagsinga nito'), [3, 4]),
    ],
    [
        choose([1], [1], T('أين محل النية؟', 'Where is the place of the intention (Niyyah)?', 'Saan ang lugar ng intensyon?'),
               [T('القلب', 'The heart', 'Ang puso'), T('اللسان', 'The tongue', 'Ang dila'),
                T('اليدان', 'The hands', 'Ang mga kamay')]),
        order([2], [1, 2, 3, 4], T('رتّب خطوات الوضوء الأربع الأولى', 'Put the first four steps of wudu in order',
                                   'Isaayos ang unang apat na hakbang ng wudhu'),
              [T('النية', 'The intention in the heart', 'Ang intensyon sa puso'),
               T('غسل الكفين', 'Washing the two hands up to the wrists', 'Ang paghugas ng kamay'),
               T('المضمضة', 'Rinsing the mouth', 'Ang pagmumog'),
               T('الاستنشاق والاستنثار', 'Sniffing water into the nose and blowing it out', 'Ang pagsinghot at pagsinga ng tubig')]),
        match([3], [3, 4], T('صِل كل كلمة بمعناها', 'Match each word with its meaning', 'Itugma ang bawat salita sa kahulugan nito'),
              [(T('المضمضة', 'Rinsing the mouth (Madmadah)', 'Ang madmada (pagmumog)'),
                T('إدخال الماء في الفم وإدارته فيه، ثم إخراجه', 'Letting water into the mouth, swirling it inside, then spitting it out',
                  'Ang pagpasok ng tubig sa bibig at pananatili sa loob nito at pagkatapos ay ilalabas ito')),
               (T('الاستنشاق', 'Istinshāq', 'Al-istinsha’q'),
                T('اجتذاب الماء بالنفس إلى أقصى الأنف', 'Sniffing water deep into the nose',
                  'Ang pagsinghut ng tubig upang papasok sa ilong')),
               (T('الاستنثار', 'Istinthār', 'Al-istinthar'),
                T('إخراج ما في الأنف من مخاط وغيره بالنفس', 'Blowing mucus and the like from the nose',
                  'Ang pagsinga ng tubig na ipinasok mula sa ilong'))]),
        choose([1], [1], T('ما معنى النية؟', 'What is the intention (Niyyah)?', 'Ano ang kahulugan ng intensyon?'),
               [T('عزم القلب على فعل العبادة تقربًا إلى الله تعالى',
                  'The resolve in the heart to perform the worship in order to get close to Allah',
                  'Ang hangarin ng puso na gawin ang isang pagsamba upang mapalapit sa Allah'),
                T('إدخال الماء في الفم وإدارته فيه', 'Letting water into the mouth and swirling it', 'Ang pagpasok ng tubig sa bibig'),
                T('اجتذاب الماء بالنفس إلى أقصى الأنف', 'Sniffing water deep into the nose', 'Ang pagsinghot ng tubig sa ilong')]),
        choose([2], [2], T('ما الخطوة التي تأتي بعد النية مباشرة؟', 'Which step comes right after the intention?',
                           'Anong hakbang ang kasunod agad ng intensyon?'),
               [T('غسل الكفين', 'Washing the two hands up to the wrists', 'Ang paghugas ng kamay'),
                T('المضمضة', 'Rinsing the mouth', 'Ang pagmumog'),
                T('الاستنشاق', 'Sniffing water into the nose', 'Ang pagsinghot ng tubig')]),
        choose([3], [4], T('إخراج ما في الأنف بالنفس يسمّى:', 'Blowing out what is in the nose is called:',
                           'Ang pagsinga ng tubig mula sa ilong ay tinatawag na:'),
               [T('الاستنثار', 'Istinthār', 'Al-istinthar'), T('المضمضة', 'Madmadah (rinsing the mouth)', 'Madmada (pagmumog)'),
                T('النية', 'Niyyah (intention)', 'Intensyon')]),
    ],
    xdrops=[X('ar', 124, reason=TITLE), X('en', 124, reason=TITLE)],
    notes='Steps 1–4 of the eight wudu steps. The Filipino text of step 2 says "three times" (tatlong beses); '
          'it stays inside the step card, not as an extra step (LRN-01 rule 3). The step label "Step N:" is '
          'not shown on the card (LRN-01 rule 3) and is listed in `dropped`.',
)

u1l4 = L(
    'u1-l4', T('أتوضأ (2): الخطوات 5–8، وما يبطل الوضوء', 'I Perform Wudu (2): Steps 5–8, and What Breaks Wudu',
               'Ako ay Nagwu-wudhu (2): Mga Hakbang 5–8, at ang Nakasisira sa Wudhu'),
    {'site_section': 'أتعلم الوضوء › tabs 5–9', 'steps': '5-8', 'page_ar': '67–73'},
    {'ar': [(132, 152)], 'en': [(132, 152)], 'tl': [(221, 251)]},
    [
        C('step', 'step 5', ar=[S(132, drop=[D('الخطوة 5: ', LBL)]), 133, 134, 135, 136],
          en=[S(132, drop=[D('Step 5: ', LBL)]), 133, 134, 135, 136], tl=[223, 224, 225, 226, 227], img='tab3_5'),
        C('text', 'step 5', ar=[137, 138, 139, 140], en=[137, 138, 139, 140], tl=[228, 229, 230, 231]),
        C('step', 'step 6', ar=[S(141, drop=[D('الخطوة 6: ', LBL)]), 142], en=[S(141, drop=[D('Step 6: ', LBL)]), 142],
          tl=[234, J(235)], img='tab3_6'),
        C('step', 'step 7', ar=[S(143, drop=[D('الخطوة 7: ', LBL)]), 144, 145, 146],
          en=[S(143, drop=[D('Step 7: ', LBL)]), 144, 145, J(146)], tl=[238, J(239)], img='tab3_7'),
        C('step', 'step 8', ar=[S(147, drop=[D('الخطوة 8: ', LBL)]), 148], en=[S(147, drop=[D('Step 8: ', LBL)]), 148],
          tl=[242], img='tab3_8'),
        C('text', 'nullifiers of wudu', ar=[149, 150, 151, 152], en=[149, 150, 151, 152],
          tl=[245, 246, J(247), 248, J(249), 250, J(251)]),
    ],
    [
        O(T('يرتّب خطوات الوضوء من الخامسة إلى الثامنة', 'Puts wudu steps five to eight in order',
            'Naisasaayos ang mga hakbang lima hanggang walo ng wudhu'), [1, 3, 4, 5], key=True),
        O(T('يعرف حدود الوجه في الوضوء وما يشمله غسله', 'Knows the boundaries of the face in wudu and what washing it includes',
            'Alam ang mga hangganan ng mukha sa wudhu at ang kasama sa paghuhugas nito'), [1, 2]),
        O(T('يعرف حدّ غسل اليدين والرجلين، وأن الرأس يُمسح مع الأذنين مرة واحدة',
            'Knows how far the hands and feet are washed, and that the head is wiped with the ears once',
            'Alam kung hanggang saan hinuhugasan ang mga kamay at paa, at na pinupunasan ang ulo kasama ang tainga nang isang beses'),
          [3, 4, 5]),
        O(T('يعرف نواقض الوضوء الثلاثة', 'Knows the three things that break wudu',
            'Alam ang tatlong bagay na nakasisira sa wudhu'), [6], key=True),
    ],
    [
        order([1], [1, 3, 4, 5], T('رتّب خطوات الوضوء من الخامسة إلى الثامنة', 'Put wudu steps five to eight in order',
                                   'Isaayos ang mga hakbang lima hanggang walo ng wudhu'),
              [T('غسل الوجه', 'Washing the face', 'Ang paghugas ng mukha'),
               T('غسل اليدين إلى المرفقين', 'Washing the hands up to the elbows', 'Ang paghugas ng dalawang kamay kasama ang siko'),
               T('مسح الرأس مع الأذنين', 'Wiping the head and the ears', 'Ang pagpunas ng ulo pati ang dalawang tainga'),
               T('غسل الرجلين إلى الكعبين', 'Washing the feet up to the ankles', 'Ang paghugas ng dalawang paa hanggang sa bukong-bukong')]),
        choose([2], [1], T('حدّ الوجه عرضًا:', 'The face, widthwise, is:', 'Ang lapad ng mukha ay:'),
               [T('من الأذن إلى الأذن', 'from one ear to the other ear', 'mula sa tainga hanggang sa kabilang tainga'),
                T('ما بين منابت شعر الرأس المعتاد إلى منتهى الذقن', 'from the usual hairline down to the end of the chin',
                  'mula sa tinutubuan ng buhok hanggang sa baba'),
                T('من رؤوس الأصابع إلى المرفقين', 'from the fingertips up to the elbows', 'mula sa mga daliri hanggang sa siko')]),
        match([2, 3], [1, 3, 5], T('صِل كل عضو بحدّه في الوضوء', 'Match each part with how far it is washed in wudu',
                                   'Itugma ang bawat bahagi sa hangganan ng paghuhugas nito sa wudhu'),
              [(T('الوجه طولًا', 'The face, lengthwise', 'Ang taas ng mukha'),
                T('ما بين منابت شعر الرأس المعتاد إلى منتهى الذقن', 'from the usual hairline on the forehead down to the end of the chin',
                  'mula sa tinutubuan ng buhok hanggang sa baba')),
               (T('اليدان', 'The hands', 'Ang dalawang kamay'),
                T('من رؤوس الأصابع إلى المرفقين', 'from the fingertips up to the elbows', 'mula sa mga daliri hanggang sa siko')),
               (T('الرجلان', 'The feet', 'Ang dalawang paa'),
                T('من أصابع القدمين إلى الكعبين', 'from the toes up to the ankles',
                  'mula sa mga daliri ng paa hanggang sa bukong-bukong'))]),
        choose([3], [3], T('هل يدخل المرفقان في غسل اليدين؟', 'Are the elbows included in washing the hands?',
                           'Kasama ba ang siko sa paghuhugas ng kamay?'),
               [T('نعم، يدخلان في الغسل المفروض', 'Yes, they are included in the obligatory washing',
                  'Oo, ang siko ay kabilang sa dapat hugasan'),
                T('لا، يُغسل الكفان إلى الرسغين فقط', 'No, only the hands up to the wrists are washed',
                  'Hindi, ang kamay lamang hanggang pulso')]),
        choose([3], [4], T('كيف يُمسح الرأس في الوضوء؟', 'How is the head wiped in wudu?', 'Paano pinupunasan ang ulo sa wudhu?'),
               [T('باليدين مع الأذنين مرة واحدة', 'With the wet hands, over the head and the ears, once',
                  'Gamit ang dalawang kamay, pati ang dalawang tainga, isang beses lamang'),
                T('تُمسح الأذنان فقط دون الرأس', 'Only the ears are wiped, not the head',
                  'Ang tainga lamang ang pinupunasan, hindi ang ulo')]),
        choose([4], [6], T('أيّ هذه من نواقض الوضوء كما في الدرس؟', 'Which of these breaks wudu, as the lesson says?',
                           'Alin dito ang nakasisira sa wudhu ayon sa aralin?'),
               [T('زوال العقل بنوم مستغرق أو إغماء', 'Loss of consciousness through deep sleep or fainting',
                  'Kawalan ng pag-iisip tulad ng mahimbing na pagtulog o pagkawala ng malay'),
                T('غسل الوجه', 'Washing the face', 'Ang paghugas ng mukha'),
                T('مسح الرأس', 'Wiping the head', 'Ang pagpunas ng ulo')]),
        match([4], [6], T('صِل كل ناقض بأمثلته', 'Match each thing that breaks wudu with its examples',
                          'Itugma ang bawat nakasisira sa wudhu sa mga halimbawa nito'),
              [(T('الخارج من السبيلين', 'What comes out of the front or back passage',
                  'Ang lumalabas mula sa unahan at likurang maseselang bahagi'),
                T('كالبول والغائط والريح', 'such as urine, feces and wind', 'tulad ng ihi, dumi at utot')),
               (T('زوال العقل', 'Loss of consciousness', 'Kawalan ng pag-iisip'),
                T('بنوم مستغرق أو إغماء أو مسكر أو جنون', 'through deep sleep, fainting, drunkenness or insanity',
                  'tulad ng mahimbing na pagtulog, pagkawala ng malay, pagkalasing o pagkawala sa tamang kaisipan')),
               (T('كل ما يوجب الغسل', 'Everything that requires Ghusl', 'Lahat ng nag-oobliga ng paligo (gusul)'),
                T('كالجنابة والحيض والنفاس', 'such as Janābah, menstruation and the postpartum period',
                  'tulad ng junub, regla at dugo dahil sa panganganak'))]),
        choose([2], [2], T('يشمل غسل الوجه:', 'Washing the face includes:', 'Kasama sa paghuhugas ng mukha ang:'),
               [T('ما فيه من شعر خفيف، والظاهر من شعر اللحية الكثيف', 'the thin hair on it, and the visible heavy hair of the beard',
                  'ang maliliit na buhok sa mukha at ang makapal na buhok ng balbas'),
                T('الرجلين إلى الكعبين', 'the feet up to the ankles', 'ang mga paa hanggang sa bukong-bukong')]),
        choose([1], [1, 3], T('ما الخطوة التي تأتي بعد غسل الوجه؟', 'Which step comes after washing the face?',
                              'Anong hakbang ang kasunod ng paghugas ng mukha?'),
               [T('غسل اليدين إلى المرفقين', 'Washing the hands up to the elbows', 'Ang paghugas ng dalawang kamay kasama ang siko'),
                T('غسل الرجلين إلى الكعبين', 'Washing the feet up to the ankles', 'Ang paghugas ng dalawang paa'),
                T('مسح الرأس مع الأذنين', 'Wiping the head and the ears', 'Ang pagpunas ng ulo at tainga')]),
    ],
    notes='Steps 5–8 and «يبطل الوضوء». Not placed in any lesson: the paragraph on cleaning oneself after '
          'relieving oneself (site tab3_10, printed p. 74) — it is outside the PRD page range (67–73) and is not '
          'in the spreadsheet; see unplaced.json. The English text of step 5 repeats the sideburns sentence in '
          'fragments (rows 137–139) and numbers the third nullifier "4-"; kept as the book has them (reviewer).',
)

u1l5 = L(
    'u1-l5', T('أتهيأ للصلاة', 'I Prepare for Prayer', 'Inihahanda Ko ang Sarili para sa Salah'),
    {'site_section': 'أتعلم الصلاة (section intro, «أتهيأ للصلاة»)', 'steps': None, 'page_ar': '90–92'},
    {'ar': [(191, 199)], 'en': [(191, 199)], 'tl': [(353, 361)]},
    [
        C('text', 'five prayers', ar=[191], en=[191], tl=[354]),
        C('text', 'purification', ar=[193, 194, 195], en=[193, 194, 195],
          tl=[356, S(357, drop=['Hadath Akbar ']), S(358, drop=['Hadath Asghar '])]),
        C('text', 'clothes and place', ar=[196, 197, 198], en=[196, 197, 198], tl=[359, 360]),
        C('text', 'manners in prayer', ar=[199], en=[S(199, drop=[" (by saying 'Subhān Allah')"])], tl=[361]),
    ],
    [
        O(T('يعرف الصلوات الخمس التي افترضها الله في اليوم والليلة', 'Knows the five prayers Allah ordained in the day and night',
            'Alam ang limang Salah na inobliga ng Allah sa bawat araw'), [1]),
        O(T('يفرّق بين الحدث الأكبر والحدث الأصغر', 'Tells major impurity apart from minor impurity',
            'Natutukoy ang pagkakaiba ng malaki at maliit na karumihan'), [2], key=True),
        O(T('يعرف ما يلبسه في الصلاة وأين يصلي وما يستره الرجل والمرأة',
            'Knows what to wear for prayer, where to pray, and what a man and a woman must cover',
            'Alam ang dapat isuot sa Salah, kung saan magdarasal, at ang dapat takpan ng lalaki at babae'), [3], key=True),
        O(T('يعرف آداب الصلاة، وما يفعله إن لم يحفظ أقوالها بعد',
            'Knows how to behave in prayer, and what to do if he has not yet memorised its words',
            'Alam ang wastong asal sa Salah, at ang gagawin kung hindi pa kabisado ang mga salita nito'), [4]),
    ],
    [
        order([1], [1], T('رتّب الصلوات الخمس كما ذكرها الدرس', 'Put the five prayers in the order the lesson gives',
                          'Isaayos ang limang Salah ayon sa pagkakasunod sa aralin'),
              [T('الفجر', 'Fajr (dawn)', 'Fajr'), T('الظهر', 'Dhuhr (noon)', 'Dhuhur'), T('العصر', '‘Asr (afternoon)', 'Asar'),
               T('المغرب', 'Maghrib (sunset)', 'Maghrib'), T('العشاء', '‘Isha’ (night)', 'Isha')]),
        choose([1], [1], T('كم صلاة افترض الله على المسلم في اليوم والليلة؟',
                           'How many prayers did Allah ordain upon the Muslim in the day and night?',
                           'Ilang Salah ang inobliga ng Allah sa isang Muslim sa bawat araw?'),
               [T('خمس صلوات', 'Five', 'Lima'), T('ثلاث صلوات', 'Three', 'Tatlo'), T('صلاة واحدة', 'One', 'Isa')]),
        match([2], [2], T('صِل كل حدث بما يوجبه', 'Match each impurity with what it requires',
                          'Itugma ang bawat karumihan sa kailangan nito'),
              [(T('الحدث الأكبر', 'Major impurity', 'Ang malaking karumihan'),
                T('يوجب الغسل', 'requires Ghusl (ritual bath)', 'nangangailangan ng Ghusl (pagligo)')),
               (T('الحدث الأصغر', 'Minor impurity', 'Ang maliit na karumihan'),
                T('يوجب الوضوء', 'requires Wudu’ (ablution)', 'nangangailangan ng Wudhu'))]),
        choose([2], [2], T('إذا دخل وقت الصلاة:', 'When the time of prayer starts:', 'Kapag pumasok ang oras ng Salah:'),
               [T('يتطهّر المسلم من الحدث الأصغر، ومن الأكبر إن كان عليه',
                  'the Muslim purifies himself from minor impurity, and from major impurity if he is in that state',
                  'dapat maging malinis ang Muslim mula sa maliit at malaking karumihan'),
                T('يصلي المسلم دون أن يتطهّر', 'the Muslim prays without purifying himself',
                  'magdarasal ang Muslim kahit hindi malinis')]),
        choose([3], [3], T('ما الذي تستره المرأة في الصلاة؟', 'What must a woman cover in prayer?',
                           'Ano ang dapat takpan ng babae sa Salah?'),
               [T('جميع بدنها إلا الوجه والكفين', 'her whole body except her face and hands',
                  'ang kanyang buong katawan maliban sa mukha at mga kamay'),
                T('ما بين السرة والركبة فقط', 'only the area between the navel and the knees',
                  'ang pagitan lamang ng pusod at tuhod')]),
        choose([3], [3], T('أين يصلي المسلم وبأي ثياب؟', 'Where does the Muslim pray, and in what clothes?',
                           'Saan at sa anong damit nagdarasal ang Muslim?'),
               [T('في مكان طاهر بثياب طاهرة ساترًا عورته', 'in a clean place, in clean clothes that cover his ‘Awra',
                  'sa malinis na lugar, sa malinis na damit na tumatakip sa kanyang Awra'),
                T('في أي مكان ولو كانت فيه نجاسة', 'anywhere, even where there is impurity',
                  'kahit saan, kahit may karumihan')]),
        choose([4], [4], T('إن لم يحفظ المسلم أقوال الصلاة بعد:', 'If the Muslim has not yet memorised the words of the prayer:',
                           'Kung hindi pa kabisado ng Muslim ang mga salita ng Salah:'),
               [T('يذكر الله ويسبّحه حتى ينتهي من الصلاة، ويبادر إلى تعلّمها',
                  'he mentions Allah and glorifies Him until the prayer ends, and hastens to learn them',
                  'aalalahanin at luluwalhatiin niya ang Allah hanggang matapos ang Salah, at magmamadaling pag-aralan ito'),
                T('يترك الصلاة حتى يحفظها', 'he leaves the prayer until he has memorised them',
                  'hindi muna siya magdarasal hanggang makabisado niya')]),
        choose([4], [4], T('في الصلاة، المسلم:', 'During prayer, the Muslim:', 'Habang nagsasalah, ang Muslim ay:'),
               [T('ينصت إلى الإمام ولا يلتفت', 'listens to the Imam and does not turn left or right',
                  'nakikinig sa Imam at hindi lumilingon'),
                T('يتحدث بغير أقوال الصلاة', 'talks with words other than the words of prayer',
                  'nagsasalita ng ibang salita bukod sa salita ng Salah')]),
    ],
    xdrops=[X('ar', 192, reason='sub-heading «أتهيأ للصلاة» = the lesson title'),
            X('en', 192, reason='sub-heading = the lesson title'),
            X('tl', 353, reason='English heading on the Filipino page (not Filipino text)'),
            X('tl', 355, reason='sub-heading = the lesson title')],
    notes='The PRD gives pp. 90–92; the first card (the five daily prayers) is the opening sentence of the '
          'prayer section just before «أتهيأ للصلاة», included so no sentence is lost. Card 4 carries the '
          'book\'s reassurance used by LRN-01 rule 2/4 (remember and glorify Allah until the words are learned); '
          'in English the transliterated "Subhān Allah" was dropped. In Filipino the terms "Hadath Akbar/Asghar" '
          '(Arabic phrases in Latin letters) were dropped; the Filipino gloss in brackets stays.',
)

u1l6 = L(
    'u1-l6', T('أصلي (1): الخطوات 1–6', 'I Pray (1): Steps 1–6', 'Ako ay Nagsasalah (1): Mga Hakbang 1–6'),
    {'site_section': 'أتعلم الصلاة › tabs 1–6', 'steps': '1-6', 'page_ar': '93–99'},
    {'ar': [(200, 206)], 'en': [(200, 206)], 'tl': [(364, 379)]},
    [
        C('step', 'step 1', ar=[S(201, drop=[D('الخطوة 1: ', LBL)]), 202], en=[S(201, drop=[D('Step 1: ', LBL)]), 202],
          tl=[365, 366]),
        C('step', 'step 2', ar=[S(203, drop=[D('الخطوة 2: ', LBL)])],
          en=[S(203, drop=[D('Step 2: ', LBL), ' and say “Allahu Akbar” (Allah is the Most Great)'])],
          tl=[S(369, drop=[' at sasabihin ang katagang: Allahu Akbar (ang Allah ang Pinakadakila)'])], img='tab10_2'),
        C('step', 'step 3', ar=[S(204, None, 'غَيْرَكَ).', drop=[D('الخطوة 3: ', LBL)])],
          en=[S(204, None, 'but You).', drop=[D('Step 3: ', LBL), ('One of the opening supplications', 'but You).')])],
          tl=[S(372, None, 'na naiulat sa Sunnah')], img='tab10_3'),
        C('step', 'step 4', ar=[S(204, 'الخطوة 4:', 'الرجيم).', drop=[D('الخطوة 4: ', LBL)])],
          en=[S(204, 'Step 4:', 'the accursed Satan).', drop=[D('Step 4: ', LBL), (', saying:', 'the accursed Satan)')])],
          tl=[S(375, None, 'Shaytan (Satanas)')], img='tab10_4'),
        C('step', 'step 5', ar=[S(204, 'الخطوة 5:', 'وهي:', drop=[D('الخطوة 5: ', LBL)])],
          en=[S(204, 'Step 5:', '(unit of the prayer):', drop=[D('Step 5: ', LBL)])],
          tl=[S(378, None, 'sa bawat raka’a:')], img='tab10_5', q=(1, 1, 7)),
        C('text', 'step 5', ar=[205], en=[205], tl=[379]),
        C('step', 'step 6', ar=[S(206, drop=[D('الخطوة 6: ', LBL)])],
          en=[S(206, drop=[D('Step 6: ', LBL), 'I say “Allahu Akbar” then ',
                           ', then I say while in Ruku‘ “Subhana rabbiy-al-azeem” (Glory is to my Lord, the Great)'])],
          tl=[S(382, drop=['Sasabihin ko: ‘’Allahuakbar ‘’ at ',
                           ', at aking sasabihin: “subhana rabbiyal azeem” (Ang kaluwalhatian ay sa aking Panginoon, ang Pinakadakila)'])],
          img='tab10_6'),
    ],
    [
        O(T('يرتّب خطوات الصلاة من الأولى إلى السادسة', 'Puts prayer steps one to six in order',
            'Naisasaayos ang mga hakbang isa hanggang anim ng Salah'), [1, 2, 3, 4, 5, 7], key=True),
        O(T('يعرف أن نية الصلاة في القلب، وأنه يستقبل القبلة ويصلي قائمًا إن قدر',
            'Knows that the intention for prayer is in the heart, and that he faces the Qiblah and prays standing if able',
            'Alam na ang intensyon ng Salah ay nasa puso, at haharap sa Qibla at magdarasal nang nakatayo kung kaya'), [1]),
        O(T('يعرف أن الفاتحة تُقرأ في كل ركعة، وأن القراءة بعدها في الركعتين الأوليين ليست بواجب',
            'Knows that al-Fātihah is recited in every rak‘ah, and that reciting more after it in the first two is not obligatory',
            'Alam na binabasa ang Al-Fatiha sa bawat raka’a, at hindi obligado ang pagbasa ng iba pa pagkatapos nito sa unang dalawang raka’a'),
          [5, 6], key=True),
        O(T('يصف هيئة الركوع', 'Describes the position of bowing (Ruku‘)', 'Nailalarawan ang tamang pagyuko'), [7]),
    ],
    [
        order([1], [1, 2, 3, 4, 5, 7], T('رتّب خطوات الصلاة من الأولى إلى السادسة', 'Put prayer steps one to six in order',
                                         'Isaayos ang mga hakbang isa hanggang anim ng Salah'),
              [T('النية واستقبال القبلة', 'The intention, and facing the Qiblah', 'Ang intensyon at pagharap sa Qibla'),
               T('رفع اليدين بمحاذاة المنكبين ناويًا الدخول في الصلاة', 'Raising the hands to shoulder level to begin the prayer',
                 'Ang pagtaas ng kamay na nakahanay sa balikat upang simulan ang Salah'),
               T('دعاء الاستفتاح', 'The opening supplication', 'Ang pambungad na Duaa'),
               T('الاستعاذة بالله من الشيطان الرجيم', 'Seeking refuge in Allah from the accursed Satan',
                 'Ang paghingi ng kanlungan kay Allah mula sa isinumpa na Shaytan'),
               T('قراءة الفاتحة', 'Reciting al-Fātihah', 'Ang pagbasa ng Al-Fatiha'),
               T('الركوع', 'Bowing (Ruku‘)', 'Ang pagyuko')]),
        choose([2], [1], T('أين محل نية الصلاة؟', 'Where is the intention for prayer made?', 'Saan ang lugar ng intensyon sa Salah?'),
               [T('في القلب', 'In the heart', 'Sa puso'), T('على اللسان', 'On the tongue', 'Sa dila'),
                T('في اليدين', 'In the hands', 'Sa mga kamay')]),
        choose([2], [1], T('بعد الوضوء، كيف أبدأ صلاتي؟', 'After wudu, how do I begin my prayer?',
                           'Pagkatapos ng wudhu, paano ko sisimulan ang aking Salah?'),
               [T('أستقبل القبلة، وأصلي قائمًا إذا كنت قادرًا', 'I face the Qiblah and pray standing if I am able',
                  'Haharap ako sa Qibla at magdarasal nang nakatayo kung kaya ko'),
                T('أصلي جالسًا ولو كنت قادرًا على القيام', 'I pray sitting even if I am able to stand',
                  'Magdarasal ako nang nakaupo kahit kaya kong tumayo')]),
        choose([3], [5], T('متى أقرأ سورة الفاتحة؟', 'When do I recite Surat al-Fātihah?', 'Kailan ko babasahin ang Surah Al-Fatiha?'),
               [T('في كل ركعة', 'In every rak‘ah', 'Sa bawat raka’a'),
                T('في الركعة الأولى فقط', 'Only in the first rak‘ah', 'Sa unang raka’a lamang'),
                T('في الركعة الأخيرة فقط', 'Only in the last rak‘ah', 'Sa huling raka’a lamang')]),
        choose([3], [6], T('قراءة شيء من القرآن بعد الفاتحة في الركعتين الأولى والثانية:',
                           'Reciting more of the Qur’an after al-Fātihah in the first and second rak‘ah is:',
                           'Ang pagbasa ng iba pang bahagi ng Qur’an pagkatapos ng Al-Fatiha sa una at ikalawang raka’a ay:'),
               [T('ليست بواجب، وفي فعلها أجر عظيم', 'not obligatory, but it brings a great reward',
                  'hindi obligado ngunit nagdudulot ng malaking gantimpala'),
                T('واجبة في كل ركعة', 'obligatory in every rak‘ah', 'obligado sa bawat raka’a')]),
        choose([4], [7], T('في الركوع يكون:', 'In Ruku‘ (bowing):', 'Sa pagyuko:'),
               [T('الظهر مستويًا، واليدان على الركبتين مفرّجة الأصابع',
                  'the back is level, and the hands are on the knees with the fingers spread out',
                  'tuwid ang likod at nakalatag ang kamay sa tuhod na nakabukas ang mga daliri'),
                T('اليدان مرفوعتين بمحاذاة المنكبين', 'the hands are raised to shoulder level',
                  'nakataas ang kamay na nakahanay sa balikat')]),
        match([1, 4], [2, 5, 7], T('صِل كل فعل بما ذكره الدرس عنه', 'Match each action with what the lesson says about it',
                                   'Itugma ang bawat gawain sa sinabi ng aralin tungkol dito'),
              [(T('رفع اليدين في أول الصلاة', 'Raising the hands at the start of prayer', 'Pagtaas ng kamay sa simula ng Salah'),
                T('بمحاذاة المنكبين', 'to the level of the shoulders', 'nakahanay sa mga balikat')),
               (T('قراءة الفاتحة', 'Reciting al-Fātihah', 'Pagbasa ng Al-Fatiha'),
                T('في كل ركعة', 'in every rak‘ah', 'sa bawat raka’a')),
               (T('الركوع', 'Bowing (Ruku‘)', 'Pagyuko'),
                T('اليدان على الركبتين', 'hands on the knees', 'kamay sa tuhod'))]),
    ],
    xdrops=[X('ar', 200, reason=TITLE), X('en', 200, reason=TITLE),
            X('tl', 372, ', at kabilang dito', None, reason=TR + ' (opening supplication) and its meaning', card=3),
            X('tl', 375, ' sa pagsasabing:', None, reason=TR, card=4)],
    notes='Steps 1–6 of the twelve prayer steps. Al-Fatiha (1:1–7) is shown from the Quran database with the '
          'audio of day-one-media.json; its Arabic text, its English transliteration+meaning and its Filipino '
          'meaning were all removed from the cards. In English and Filipino every dhikr written in Latin '
          'letters was dropped together with its meaning (see `dropped`); the Arabic cards keep the adhkar in '
          'Arabic. Where a dropped clause was "I say Allahu Akbar and …", the card now starts with the action.',
)

u1l7 = L(
    'u1-l7', T('أصلي (2): الخطوات 7–12', 'I Pray (2): Steps 7–12', 'Ako ay Nagsasalah (2): Mga Hakbang 7–12'),
    {'site_section': 'أتعلم الصلاة › tabs 7–13', 'steps': '7-12', 'page_ar': '100–107'},
    {'ar': [(207, 213)], 'en': [(207, 213)], 'tl': [(383, 406)]},
    [
        C('step', 'step 7', ar=[S(207, drop=[D('الخطوة 7: ', LBL)])],
          en=[S(207, drop=[D('Step 7: ', LBL), ' while saying: “Sami‘ Allahu liman hamidah” (Allah hears the one who praises him)',
                           ' When I stand straight, I say: “Rabbanā wa lak al-hamd” (Our Lord, and to You is all praise).'])],
          tl=[S(385, drop=[' at sasabihin: “Sami ‘Allahu liman hamidah” (dininig ng Allah ang sinumang pumuri sa kanya)',
                           ', at kung ang aking katawan ay ganap nang nakatayo, sasabihin ko: “Rabbana walakal hamdu” (Panginoon namin, tanging sa Iyo lamang ang papuri)'])],
          img='tab10_7'),
        C('step', 'step 8', ar=[S(208, drop=[D('الخطوة 8: ', LBL)])],
          en=[S(208, drop=[D('Step 8: ', LBL), 'I say “Allahu Akbar” and ',
                           ', then I say while prostrating: “Subhāna rabbiy-al-a‘la” (Glory is to my Lord, the Most High)'])],
          tl=[S(388, drop=['Sasabihin ko ang ‘’Allahuakbar’’ at ',
                           ', at sasabihin ko sa aking pagpatirapa: ‘’Subhana rabbiyal A’lah ‘’ (Luwalhati sa aking Panginoon, ang Kataas-taasan)'])],
          img='tab10_8'),
        C('step', 'step 9', ar=[S(209, drop=[D('الخطوة 9: ', LBL)])],
          en=[S(209, drop=[D('Step 9: ', LBL), 'I say “Allahu Akbar” and ', ' and say: “Rabbi ighfir lī” (My Lord, forgive my sins)'])],
          tl=[S(391, drop=['Sasabihin ko: ‘’Allahukbar’’ at ',
                           ', at bibigkasin ang katagang: “rabbi ighfir li” (Panginoon, patawarin mo ako)'])],
          img='tab10_9'),
        C('step', 'step 10', ar=[S(210, drop=[D('الخطوة 10: ', LBL)])],
          en=[S(210, drop=[D('Step 10: ', LBL), 'I say “Allahu Akbar” and '])],
          tl=[S(394, drop=['Sasabihin ko: ‘’Allahukbar’’ at '])], img='tab10_10'),
        C('step', 'step 11', ar=[S(211, drop=[D('الخطوة 11: ', LBL)])],
          en=[S(211, drop=[D('Step 11: ', LBL), ' while saying “Allahu Akbar”'])],
          tl=[S(397, drop=[' at sasabihin: ‘’Allahukbar’’'])], img='tab10_11'),
        C('text', 'step 11 (first tashahhud)', ar=[S(212, None, 'للركعة الثالثة بعد ذلك.')],
          en=[S(212, None, 'for the third Rak‘ah.', drop=[(' whose wording is as follows:', 'His slave and Messenger)')])],
          tl=[S(401, drop=[(': (At-Tahiy', 'rasuluh)')]), S(402, 'Pagkatapos ay lilipat', 'pangatlong rakaa,')],
          img='tab10_12'),
        C('text', 'step 11 (last tashahhud)', ar=[S(212, 'بعد الركعة الأخيرة')],
          en=[S(212, 'After the second prostration in the last',
                drop=[D(' whose wording is as follows', 'words introducing the dropped dhikr'),
                      (': “At-tahiyyātu', 'Full of Glory).')])],
          tl=[S(402, 'sa huling rakaa', 'sumusunod na pagbigkas')]),
        C('step', 'step 12', ar=[S(213, drop=[D('الخطوة 12: ', LBL)])],
          en=[S(213, drop=[D('Final Step: ', LBL),
                           ', saying: “As-salāmu ‘alaykum wa rahmatullāh” (Peace and blessings of Allah be upon you)',
                           ', saying: “As-salāmu ‘alaykum wa rahmatullāh"'])],
          tl=[S(406, drop=[' sa pamamagitan ng pagsasabi ng: “As-salamu ʿalaikum wa rahmatu-llah,” ang kapayapaan at mga pagpapala ng Allah ay sumaiyo,'])],
          img='tab10_13'),
    ],
    [
        O(T('يرتّب خطوات الصلاة من السابعة إلى الثانية عشرة', 'Puts prayer steps seven to twelve in order',
            'Naisasaayos ang mga hakbang pito hanggang labindalawa ng Salah'), [1, 2, 3, 4, 5, 8], key=True),
        O(T('يصف هيئة السجود والجلوس بين السجدتين', 'Describes prostration and the sitting between the two prostrations',
            'Nailalarawan ang pagpapatirapa at ang pag-upo sa pagitan ng dalawang pagpapatirapa'), [2, 3]),
        O(T('يعرف متى يجلس للتشهد الأول ومتى يجلس للتشهد الأخير', 'Knows when to sit for the first Tashahhud and when for the last',
            'Alam kung kailan uupo para sa unang Tashahud at para sa huli'), [6, 7], key=True),
        O(T('يعرف كيف يختم الصلاة عن يمينه ثم عن شماله', 'Knows how to end the prayer by turning to the right, then to the left',
            'Alam kung paano tapusin ang Salah sa pagharap sa kanan at pagkatapos sa kaliwa'), [8]),
    ],
    [
        order([1], [1, 2, 3, 4, 5, 8], T('رتّب خطوات الصلاة من السابعة إلى الثانية عشرة', 'Put prayer steps seven to twelve in order',
                                         'Isaayos ang mga hakbang pito hanggang labindalawa ng Salah'),
              [T('الرفع من الركوع', 'Rising from Ruku‘', 'Ang pagtayo mula sa pagkayuko'),
               T('السجود', 'Prostration', 'Ang pagpapatirapa'),
               T('الجلوس بين السجدتين', 'Sitting between the two prostrations', 'Ang pag-upo pagkatapos ng unang pagpapatirapa'),
               T('السجدة الثانية', 'The second prostration', 'Ang ikalawang pagpapatirapa'),
               T('القيام لبقية ركعات الصلاة', 'Standing up for the rest of the prayer', 'Ang pagtayo para sa natitirang mga raka’a'),
               T('التسليم عن اليمين ثم عن الشمال', 'Turning to the right, then to the left, to end the prayer',
                 'Ang pagtatapos ng Salah sa kanan at sa kaliwa')]),
        choose([2], [2], T('على أي شيء يكون السجود؟', 'On what does one prostrate?', 'Sa ano nagpapatirapa?'),
               [T('على اليدين والركبتين والقدمين والجبهة والأنف', 'On the hands, knees, feet, forehead and nose',
                  'Sa mga kamay, tuhod, paa, noo at ilong'),
                T('على اليدين والركبتين فقط', 'On the hands and knees only', 'Sa mga kamay at tuhod lamang'),
                T('على الجبهة فقط', 'On the forehead only', 'Sa noo lamang')]),
        choose([2], [3], T('كيف أجلس بين السجدتين؟', 'How do I sit between the two prostrations?',
                           'Paano ako uupo sa pagitan ng dalawang pagpapatirapa?'),
               [T('على القدم اليسرى، ناصبًا القدم اليمنى، مستقيم الظهر', 'On my left foot, with my right foot erect and my back straight',
                  'Nakaupo sa kaliwang paa, nakataas ang kanang paa, at tuwid ang likod'),
                T('على القدم اليمنى، ناصبًا القدم اليسرى', 'On my right foot, with my left foot erect',
                  'Nakaupo sa kanang paa, nakataas ang kaliwang paa')]),
        choose([3], [6], T('متى أجلس للتشهد الأول؟', 'When do I sit for the first Tashahhud?', 'Kailan ako uupo para sa unang Tashahud?'),
               [T('بعد الركعة الثانية من الظهر والعصر والمغرب والعشاء', 'After the second rak‘ah of Dhuhr, ‘Asr, Maghrib and ‘Isha’',
                  'Pagkatapos ng ikalawang raka’a ng Dhuhr, Asr, Maghrib at Isha'),
                T('بعد الركعة الأولى من كل صلاة', 'After the first rak‘ah of every prayer', 'Pagkatapos ng unang raka’a ng bawat Salah')]),
        match([3, 4], [6, 7, 8], T('صِل كل موضع بما أفعله فيه', 'Match each point in the prayer with what I do there',
                                   'Itugma ang bawat bahagi ng Salah sa gagawin ko roon'),
              [(T('بعد الركعة الثانية من الظهر والعصر والمغرب والعشاء', 'After the second rak‘ah of Dhuhr, ‘Asr, Maghrib and ‘Isha’',
                  'Pagkatapos ng ikalawang raka’a ng Dhuhr, Asr, Maghrib at Isha'),
                T('أجلس للتشهد الأول، ثم أقوم للركعة الثالثة', 'I sit for the first Tashahhud, then stand up for the third rak‘ah',
                  'Uupo ako para sa unang Tashahud, pagkatapos ay lilipat sa pangatlong raka’a')),
               (T('بعد الركعة الأخيرة من كل صلاة', 'After the last rak‘ah of every prayer', 'Sa huling raka’a ng bawat Salah'),
                T('أجلس للتشهد الأخير', 'I sit for the last Tashahhud', 'Uupo ako para sa Tashahud ng huling raka’a')),
               (T('بعد التشهد الأخير', 'After the last Tashahhud', 'Pagkatapos ng huling Tashahud'),
                T('أسلّم عن يميني ثم عن شمالي ناويًا الخروج من الصلاة', 'I turn my head to the right, then to the left, to end the prayer',
                  'Haharap ako sa kanan at sa kaliwa upang tapusin ang Salah'))]),
        choose([4], [8], T('كيف أختم الصلاة؟', 'How do I end the prayer?', 'Paano ko tatapusin ang Salah?'),
               [T('أسلّم عن يميني ثم عن شمالي ناويًا الخروج من الصلاة',
                  'I turn my head to the right, then to the left, intending to end the prayer',
                  'Haharap ako sa kanan at pagkatapos sa kaliwa upang tapusin ang Salah'),
                T('أسلّم عن يميني فقط', 'I turn to the right only', 'Haharap lamang ako sa kanan')]),
        choose([1], [5, 4], T('بعد السجدة الثانية من الركعة الأولى في الفريضة:',
                              'After the second prostration of the first rak‘ah of an obligatory prayer:',
                              'Pagkatapos ng ikalawang pagpapatirapa sa unang raka’a ng obligadong Salah:'),
               [T('أقوم حتى أستقيم واقفًا، وأفعل في بقية الركعات مثل ما فعلت في الأولى',
                  'I rise to stand up straight, and repeat the same steps in the remaining units',
                  'Tatayo ako nang tuwid at gagawin ang natitirang mga raka’a tulad ng ginawa ko sa unang raka’a'),
                T('أختم الصلاة مباشرة', 'I end the prayer straight away', 'Tatapusin ko agad ang Salah')]),
        match([2, 1], [1, 2, 3], T('صِل كل حركة بوصفها', 'Match each movement with its description',
                                   'Itugma ang bawat galaw sa paglalarawan nito'),
              [(T('الرفع من الركوع', 'Rising from Ruku‘', 'Pagtayo mula sa pagkayuko'),
                T('رافعًا يديّ إلى حذو المنكبين', 'raising my hands to the level of my shoulders',
                  'itataas ko ang aking mga kamay sa antas ng balikat')),
               (T('السجود', 'Prostration', 'Pagpapatirapa'),
                T('على اليدين والركبتين والقدمين والجبهة والأنف', 'on the hands, knees, feet, forehead and nose',
                  'gamit ang mga kamay, tuhod, paa, noo at ilong')),
               (T('الجلوس بين السجدتين', 'Sitting between the prostrations', 'Pag-upo sa pagitan ng pagpapatirapa'),
                T('على القدم اليسرى ناصبًا اليمنى', 'on the left foot, with the right foot erect',
                  'sa kaliwang paa, nakataas ang kanang paa'))]),
    ],
    xdrops=[X('tl', 400, reason='duplicate of the step-11 text, wrongly repeated inside the step-12 tab of the Filipino page'),
            X('tl', 402, None, 'Kanyang lingkod at sugo.”', reason=MEANING, card=6),
            X('tl', 402, ': (Allaahumma', None, reason=TR, card=7),
            X('tl', 403, reason=MEANING, card=7)],
    notes='Steps 7–12. As in the printed book, step 11 includes the two Tashahhud paragraphs (cards 6–7, '
          'source_ref "step 11"); the site shows them as a separate 12th tab, which is why the site has 13 tabs '
          'for 12 steps. English/Filipino adhkar (transliteration and their meaning) were dropped; the Arabic '
          'cards keep the full Tashahhud in Arabic. Filipino card 8 reads awkwardly after the drop and the '
          'Filipino last-Tashahhud card ends with "…in addition to the following recitation" (reviewer).',
)

LESSONS = [u1l1, u1l2, u1l3, u1l4, u1l5, u1l6, u1l7]
