"""Unit 4 — أركان الإيمان (LRN-09). Line numbers: ar/en = spreadsheet rows, tl = site lines."""
from build import S, J, D, Q, X, C, O, L, T, choose, order, match

QUOTE = ('Quran wording in braces inside the English translation (the Arabic states it as plain prose); '
         'verse text is never copied into cards')

u4l1 = L(
    'u4-l1', T('الإيمان بالله', 'Belief in Allah', 'Ang Paniniwala sa Allah'),
    {'site_section': 'أتعرف على أركان الإيمان (intro) + الركن الأول (tab6_1)', 'steps': None, 'page_ar': '42–47'},
    {'ar': [(73, 83)], 'en': [(73, 83)], 'tl': [(116, 131)]},
    [
        C('text', 'iman intro', ar=[S(73, None, 'خيره وشره).')], en=[S(73, None, 'the good and the bad thereof.”')], tl=[116]),
        C('text', 'iman intro', ar=[S(73, 'أركان الإيمان هي')], en=[S(73, 'The pillars of Imān are')], tl=[117]),
        C('text', 'iman intro', ar=[74, 75], en=[74, J(75)], tl=[118, 119]),
        C('text', 'iman intro', ar=[76], en=[76], tl=[120]),
        C('text', 'iman pillar 1', ar=[77, S(78, None, 'قال تعالى:')], en=[77, S(78, None, 'Allah Almighty says:')],
          tl=[124, 125, S(126, None, 'Sinabi ng Allah:')], q=(24, 62, 62)),
        C('text', 'iman pillar 1', ar=[79, 80, 81], en=[79, 80, 81],
          tl=[S(127, drop=[' (Asmaa was sifaat)']), 128, 129]),
        C('text', 'iman pillar 1', ar=[82, 83],
          en=[82, S(83, drop=[D(', and that {there is nothing like unto Him and He is the All-Hearing, the All-Seeing}', QUOTE)])],
          tl=[130, 131]),
    ],
    [
        O(T('يعدّد أركان الإيمان الستة', 'Lists the six pillars of faith', 'Naiisa-isa ang anim na haligi ng Iman'), [1, 3], key=True),
        O(T('يفرّق بين أركان الإسلام وأركان الإيمان', 'Tells the pillars of Islam apart from the pillars of faith',
            'Natutukoy ang pagkakaiba ng mga haligi ng Islam at ng Iman'), [2]),
        O(T('يعرف تعريف الإيمان المختصر وأنه يزيد وينقص', 'Knows the short definition of faith and that it increases and decreases',
            'Alam ang maikling kahulugan ng Iman at na ito ay tumataas at bumababa'), [4, 3]),
        O(T('يعرف ما يتضمنه الإيمان بالله: وجوده وربوبيته وألوهيته وأسماؤه وصفاته',
            'Knows what belief in Allah includes: His existence, Lordship, sole right to worship, and Names and Attributes',
            'Alam ang kasama sa paniniwala sa Allah: ang Kanyang pag-iral, pagka-Panginoon, pagka-Diyos, at mga pangalan at katangian'),
          [5, 6, 7], key=True),
    ],
    [
        order([1], [1, 3], T('رتّب أركان الإيمان كما في الحديث', 'Put the pillars of faith in the order of the hadith',
                             'Isaayos ang mga haligi ng Iman ayon sa hadith'),
              [T('الإيمان بالله', 'Belief in Allah', 'Paniniwala sa Allah'),
               T('وملائكته', 'His angels', 'sa Kanyang mga anghel'),
               T('وكتبه', 'His Books', 'sa Kanyang mga aklat'),
               T('ورسله', 'His Messengers', 'sa Kanyang mga Sugo'),
               T('واليوم الآخر', 'the Last Day', 'sa Huling Araw'),
               T('والقدر خيره وشره', 'preordainment, the good and the bad thereof', 'sa tadhana, mabuti man o masama')]),
        choose([1], [1], T('كم ركنًا للإيمان ذكر الحديث؟', 'How many pillars of faith does the hadith name?',
                           'Ilang haligi ng Iman ang binanggit sa hadith?'),
               [T('ستة', 'Six', 'Anim'), T('خمسة', 'Five', 'Lima'), T('أربعة', 'Four', 'Apat')]),
        match([2], [2], T('صِل كل نوع من الأركان بوصفه', 'Match each kind of pillar with its description',
                          'Itugma ang bawat uri ng haligi sa paglalarawan nito'),
              [(T('أركان الإسلام', 'The pillars of Islam', 'Ang mga haligi ng Islam'),
                T('أعمال ظاهرة يؤديها الإنسان بجوارحه، كالنطق بالشهادتين والصلاة والزكاة',
                  'visible acts done by the body parts, like the Shahādah, prayer and Zakah',
                  'mga gawaing lantad na isinasagawa ng katawan, tulad ng Shahadatyn, Salah at Zakah')),
               (T('أركان الإيمان', 'The pillars of faith', 'Ang mga haligi ng Iman'),
                T('أعمال قلبية يؤديها الإنسان بقلبه، مثل الإيمان بالله وكتبه ورسله',
                  'acts of the heart, like belief in Allah, His Books and His Messengers',
                  'mga gawain ng puso, tulad ng paniniwala sa Allah, sa Kanyang mga kasulatan at mga sugo'))]),
        choose([2], [2], T('الصلاة والزكاة من:', 'Prayer and Zakah are:', 'Ang Salah at Zakah ay:'),
               [T('أركان الإسلام، وهي أعمال ظاهرة', 'pillars of Islam: visible acts', 'mga haligi ng Islam: mga gawaing lantad'),
                T('أركان الإيمان، وهي أعمال قلبية', 'pillars of faith: acts of the heart', 'mga haligi ng Iman: mga gawain ng puso'), T('ليست من أركان الدين', 'Not pillars of the religion at all', 'Hindi mga haligi ng relihiyon')]),
        choose([3], [4], T('الإيمان يزيد … وينقص …', 'Faith increases by … and decreases by …', 'Ang Iman ay tumataas sa … at bumababa sa …'),
               [T('بالطاعة / بالمعصية', 'obedience / disobedience', 'pagsunod / pagsuway'),
                T('بالمعصية / بالطاعة', 'disobedience / obedience', 'pagsuway / pagsunod'), T('بكثرة المال / بقلّة المال', 'With wealth / with poverty', 'Sa yaman / sa kahirapan')]),
        match([3], [4, 3], T('صِل كل جزء من تعريف الإيمان بموضعه', 'Match each part of the definition of faith with where it is',
                             'Itugma ang bawat bahagi ng kahulugan ng Iman sa kinalalagyan nito'),
              [(T('اعتقاد', 'Belief', 'Paniniwala'), T('بالقلب', 'of the heart', 'ng puso')),
               (T('قول', 'Statement', 'Pagsambit'), T('باللسان', 'of the tongue', 'ng dila')),
               (T('عمل', 'Action', 'Pagkilos'), T('بالجوارح', 'of the body parts', 'ng katawan'))]),
        match([4], [6, 7], T('صِل كل جانب من الإيمان بالله بمعناه', 'Match each part of belief in Allah with its meaning',
                             'Itugma ang bawat bahagi ng paniniwala sa Allah sa kahulugan nito'),
              [(T('الإيمان بربوبيته', 'Belief that He is the only Lord', 'Paniniwala sa Kanyang pagka-Panginoon'),
                T('أنه مالك كل شيء وخالقه ورازقه ومدبّر أمره', 'He is the Owner, Creator and Sustainer of everything, Who manages its affairs',
                  'Siya ang nagmamay-ari, lumikha, nagbigay biyaya at nangangasiwa sa lahat')),
               (T('الإيمان بألوهيته', 'Belief that He is the only God', 'Paniniwala sa Kanyang pagka-Diyos'),
                T('أنه المستحق للعبادة وحده لا شريك له', 'He alone deserves to be worshiped, without partners',
                  'sa Kanya lamang iaalay ang lahat ng uri ng pagsamba')),
               (T('الإيمان بأسمائه وصفاته', 'Belief in His Names and Attributes', 'Paniniwala sa Kanyang mga pangalan at katangian'),
                T('التي أثبتها لنفسه أو أثبتها له نبيه ﷺ', 'those He affirmed for Himself or His Prophet affirmed for Him',
                  'na inilarawan Niya sa Kanyang sarili at ng Kanyang sugo'))]),
        choose([4], [7, 5], T('أيّ العبادات تكون لله وحده؟', 'Which acts of worship are for Allah alone?',
                              'Aling mga pagsamba ang para lamang sa Allah?'),
               [T('الصلاة والدعاء والنذر والذبح، وجميع العبادات', 'Prayer, supplication, vows, sacrifice — all acts of worship',
                  'Pagdarasal, pananalangin, panata, pagkatay — lahat ng uri ng pagsamba'),
                T('الصلاة وحدها', 'Prayer only', 'Ang pagdarasal lamang'),
                T('الدعاء وحده', 'Supplication only', 'Ang pananalangin lamang')]),
    ],
    notes='Intro of «أتعرف على أركان الإيمان» and the first pillar. English card 7: the closing words were set '
          'in braces as a Quran quotation ({there is nothing like unto Him…}) and were dropped; the Arabic keeps '
          'the same words because it states them as prose (reviewer). Filipino card 6: the phrase "(Asmaa was '
          'sifaat)" (Arabic in Latin letters) was dropped; single-word terms (Ruboobeeyah, Uluhiyah) stay.',
)

u4l2 = L(
    'u4-l2', T('الملائكة والكتب', 'The Angels and the Scriptures', 'Ang mga Anghel at ang mga Aklat'),
    {'site_section': 'أتعرف على أركان الإيمان › الركن الثاني والثالث (tab6_2, tab6_3)', 'steps': None, 'page_ar': '48–53'},
    {'ar': [(84, 98)], 'en': [(84, 98)], 'tl': [(133, 154)]},
    [
        C('text', 'iman pillar 2', ar=[84, S(85, None, 'قال تعالى:')], en=[84, S(85, None, 'Allah Almighty says:')],
          tl=[133, 134, S(135, None, 'Sinabi ng Allah:')], q=(35, 1, 1)),
        C('text', 'iman pillar 2', ar=[86], en=[86], tl=[136]),
        C('text', 'iman pillar 2', ar=[87], en=[87], tl=[137]),
        C('text', 'iman pillar 3', ar=[88, S(89, None, 'قال تعالى:')], en=[88, S(89, None, 'Allah Almighty says:')],
          tl=[139, 140, S(141, None, 'Sinabi ng Allah:')], q=(2, 136, 136)),
        C('text', 'iman pillar 3', ar=[90, 91], en=[90, J(91)], tl=[S(142, None, 'malinaw na katotohanan.')]),
        C('text', 'iman pillar 3', ar=[S(92, None, 'فقال تعالى:')], en=[S(92, None, 'He says:')],
          tl=[S(142, 'Sa pagpadala', 'Sinabi ng Allah:')], q=(15, 9, 9)),
        C('text', 'iman pillar 3', ar=[S(92, 'لأن القرآن', 'قال تعالى:')], en=[S(92, 'This is because', 'Allah Almighty says:')],
          tl=[S(143, None, 'sinabi ng Allah:')], q=(3, 19, 19)),
        C('text', 'iman pillar 3', ar=[93, 94, 95, 96, 97, 98], en=[93, 94, 95, 96, 97, 98],
          tl=[144, 145, J(146), 147, J(148), 149, J(150), 151, J(152), 153, J(154)]),
    ],
    [
        O(T('يعرف أن الملائكة عالم غيبي، عباد لله خلقهم من نور، لا يحيط بعددهم إلا الله',
            'Knows that the angels are of the unseen, servants of Allah created from light, whose number only Allah knows',
            'Alam na ang mga anghel ay di nakikitang nilalang, nilikha ng Allah mula sa liwanag, at Siya lamang ang nakaaalam ng kanilang bilang'),
          [2, 3, 1], key=True),
        O(T('يعرف أن جبريل عليه السلام الموكّل بالوحي', 'Knows that Jibreel (peace be upon him) is assigned with the revelation',
            'Alam na si Jibril ang itinalaga sa pagpapahayag ng rebelasyon'), [3]),
        O(T('يعرف معنى الإيمان بالكتب، وأن القرآن آخرها وقد تكفّل الله بحفظه',
            'Knows what belief in the Scriptures means, and that the Qur’an is the last of them and Allah guaranteed to protect it',
            'Alam ang kahulugan ng paniniwala sa mga Aklat, at na ang Qur’an ang huli at pinangangalagaan ito ng Allah'),
          [5, 6, 7, 4], key=True),
        O(T('يطابق الكتب السماوية بالأنبياء الذين أُنزلت عليهم', 'Matches the divine Scriptures with the prophets they were revealed to',
            'Naitutugma ang mga Aklat sa mga propeta na pinagbabaan nito'), [8]),
    ],
    [
        match([1, 2], [2, 3], T('صِل كلًّا بما يصفه', 'Match each with its description', 'Itugma ang bawat isa sa paglalarawan nito'),
              [(T('الملائكة', 'The angels', 'Ang mga anghel'), T('عالم غيبي', 'are part of the unseen realm', 'ay di nakikitang nilalang')),
               (T('خلقهم الله', 'Allah created them', 'Nilikha sila ng Allah'), T('من نور', 'from light', 'mula sa liwanag')),
               (T('جبريل عليه السلام', 'Jibreel', 'Si Jibril'),
                T('الموكّل بالوحي', 'is assigned with delivering the revelation', 'ay itinalaga sa pagpapahayag ng rebelasyon'))]),
        choose([1], [3, 1], T('مَن يحيط بقوة الملائكة وعددهم؟', 'Who knows the number and abilities of the angels?',
                           'Sino ang nakaaalam ng tunay na lakas at bilang ng mga anghel?'),
               [T('الله تعالى وحده', 'Allah alone', 'Ang Allah lamang'), T('الناس', 'People', 'Ang mga tao'),
                T('جبريل عليه السلام', 'Jibreel', 'Si Jibril')]),
        choose([2], [3], T('مَن الموكّل بالوحي من الملائكة؟', 'Which angel is assigned with the revelation?',
                           'Sinong anghel ang itinalaga sa rebelasyon?'),
               [T('جبريل عليه السلام', 'Jibreel', 'Si Jibril'), T('موسى عليه السلام', 'Moses', 'Si Musa'),
                T('إبراهيم عليه السلام', 'Abraham', 'Si Ibrahim')]),
        choose([3], [5, 4], T('الإيمان بالكتب هو التصديق الجازم بأن:', 'Belief in the Scriptures is the firm belief that:',
                              'Ang paniniwala sa mga Aklat ay ang matibay na paniniwala na:'),
               [T('جميع الكتب السماوية كلام الله، منزّلة من عنده على رسله', 'all the divine Scriptures are the word of Allah, revealed by Him to His messengers',
                  'ang lahat ng mga kapahayagan ay salita ng Allah, ibinaba sa Kanyang mga Sugo'),
                T('الكتب السماوية ليست من عند الله', 'the divine Scriptures are not from Allah', 'ang mga kapahayagan ay hindi mula sa Allah'), T('القرآن وحده كلام الله دون الكتب التي قبله', 'Only the Quran is Allah’s speech, not the books before it', 'Ang Quran lamang ang salita ni Allah at hindi ang mga naunang kasulatan')]),
        choose([3], [6], T('مَن تكفّل بحفظ القرآن الكريم من التبديل والتحريف؟', 'Who guaranteed to protect the Qur’an against distortion and alteration?',
                           'Sino ang nangangalaga sa Qur’an mula sa anumang pagbabago?'),
               [T('الله تعالى', 'Allah', 'Ang Allah'), T('الناس', 'People', 'Ang mga tao'), T('العلماء وحدهم', 'The scholars alone', 'Ang mga iskolar lamang')]),
        choose([3], [7], T('لماذا جعل الله القرآن مهيمنًا على الكتب السابقة؟', 'Why did Allah make the Qur’an supersede the earlier Scriptures?',
                           'Bakit ginawa ng Allah na mangibabaw ang Qur’an sa mga naunang kapahayagan?'),
               [T('لأنه آخر كتب الله إلى البشر، ومحمد ﷺ آخر الرسل', 'Because it is the last revelation to mankind, and Muhammad ﷺ is the last Messenger',
                  'Dahil ito ang huling kapahayagan ng Allah, at si Muhammad ang huling sugo'),
                T('لأنه أول كتب الله', 'Because it is the first of Allah’s Books', 'Dahil ito ang unang aklat ng Allah'), T('لأنه أطول الكتب', 'Because it is the longest book', 'Dahil ito ang pinakamahabang aklat')]),
        match([4], [8], T('صِل كل كتاب بالنبي الذي أُنزل عليه', 'Match each Scripture with the prophet it was revealed to',
                          'Itugma ang bawat aklat sa propeta na pinagbabaan nito'),
              [(T('القرآن الكريم', 'The Noble Qur’an', 'Ang Qur’an'), T('محمد ﷺ', 'Muhammad (pbuh)', 'Muhammad ﷺ')),
               (T('التوراة', 'The Torah', 'Ang Tawrah'), T('موسى عليه السلام', 'Moses', 'Musa')),
               (T('الإنجيل', 'The Gospel', 'Ang Injeel'), T('عيسى عليه السلام', 'Jesus', 'Eesa')),
               (T('الزبور', 'The Psalms', 'Ang Zaboor'), T('داوود عليه السلام', 'David', 'Dawood'))]),
        choose([4], [8], T('على مَن أُنزلت صحف إبراهيم؟', 'To whom were the Scrolls of Abraham revealed?',
                           'Kanino ipinadala ang Suhoof?'),
               [T('إبراهيم عليه السلام', 'Abraham', 'Kay Ibrahim'), T('موسى عليه السلام', 'Moses', 'Kay Musa'),
                T('عيسى عليه السلام', 'Jesus', 'Kay Eesa')]),
    ],
    notes='Pillars 2 and 3. Verses 35:1, 2:136, 15:9 and 3:19 are shown from the Quran database. The Arabic site '
          'says the Psalms (الزبور) were revealed to «عيسى»; the spreadsheet and the printed book say «داوود», as do '
          'the English and Filipino — the spreadsheet wording is used (README).',
)

u4l3 = L(
    'u4-l3', T('الرسل واليوم الآخر', 'The Messengers and the Last Day', 'Ang mga Sugo at ang Huling Araw'),
    {'site_section': 'أتعرف على أركان الإيمان › الركن الرابع والخامس (tab6_4, tab6_5)', 'steps': None, 'page_ar': '54–56'},
    {'ar': [(99, 106)], 'en': [(99, 106)], 'tl': [(156, 166)]},
    [
        C('text', 'iman pillar 4', ar=[99, S(100, None, 'قال تعالى:')], en=[99, S(100, None, 'Allah Almighty says:')],
          tl=[156, 157, S(158, None, 'Sinabi ng Allah:')], q=(16, 36, 36)),
        C('text', 'iman pillar 4', ar=[101], en=[101], tl=[159]),
        C('text', 'iman pillar 4', ar=[102], en=[102], tl=[160]),
        C('text', 'iman pillar 4', ar=[103], en=[103], tl=[161]),
        C('text', 'iman pillar 5', ar=[104, S(105, None, 'قال تعالى:')], en=[104, S(105, None, 'Allah Almighty says:')],
          tl=[163, 164, S(165, None, 'Sinabi ng Allah:')], q=(4, 87, 87)),
        C('text', 'iman pillar 5', ar=[106], en=[106], tl=[166]),
    ],
    [
        O(T('يعرف أن الله بعث في كل أمة رسولًا يدعو إلى عبادة الله وحده', 'Knows that Allah sent a messenger to every nation calling to worship Allah alone',
            'Alam na nagpadala ang Allah sa bawat sambayanan ng Sugo na nag-aanyaya sa pagsamba sa Allah lamang'), [2, 1], key=True),
        O(T('يعرف صفات الرسل كما في الدرس', 'Knows the qualities of the messengers given in the lesson',
            'Alam ang mga katangian ng mga sugo ayon sa aralin'), [3]),
        O(T('يعرف أن دعوة الرسل كلهم واحدة في أصل الدين', 'Knows that all the messengers called to the same principle of religion',
            'Alam na iisa ang paanyaya ng lahat ng mga sugo sa pundasyon ng pananampalataya'), [4]),
        O(T('يذكر أمثلة مما يشمله الإيمان باليوم الآخر', 'Gives examples of what belief in the Last Day includes',
            'Nakapagbibigay ng mga halimbawa ng kasama sa paniniwala sa Huling Araw'), [6, 5], key=True),
    ],
    [
        match([1, 2, 3], [2, 3, 4], T('صِل كل عبارة بما يتمّ معناها', 'Match each statement with what completes its meaning', 'Itugma ang bawat pahayag sa kukumpleto ng kahulugan nito'),
              [(T('بعث الله في كل أمة', 'Allah sent to every nation', 'Nagpadala ang Allah sa bawat sambayanan'),
                T('رسولًا يدعوهم إلى عبادة الله وحده', 'a messenger to call them to worship Allah alone',
                  'ng Sugo na nag-aanyaya sa pagsamba lamang sa Allah')),
               (T('أيّد الله الرسل', 'Allah supported the messengers', 'Pinagkalooban ng Allah ang mga sugo'),
                T('بالمعجزات الدالة على صدقهم', 'with miracles that prove their truthfulness', 'ng mga himala bilang patunay na sila ay tunay na sugo')),
               (T('اتفقت دعوة الرسل من أولهم إلى آخرهم', 'The call of the messengers, from the first to the last', 'Ang paanyaya ng mga naunang Sugo at ng mga nahuli'),
                T('في أصل الدين: توحيد الله في العبادة', 'shared one principle: worshipping Allah alone',
                  'ay nagkaisa sa pundasyon: ang kaisahan ng Allah sa pagsamba'))]),
        choose([1], [2, 1], T('إلى ماذا دعا كل رسول أمته؟', 'What did every messenger call his nation to?',
                              'Saan nag-anyaya ang bawat sugo sa kanyang sambayanan?'),
               [T('إلى عبادة الله وحده لا شريك له، والكفر بما يُعبد من دونه', 'To worship Allah alone, and to reject anything worshiped other than Him',
                  'Sa pagsamba lamang sa Allah at pagtakwil ng pagsamba sa iba'),
                T('إلى أصل دين يختلف من رسول إلى آخر', 'To a principle of religion that differed from one messenger to another',
                  'Sa pundasyon ng pananampalataya na iba-iba sa bawat sugo'), T('إلى عبادة الملائكة', 'To worship the angels', 'Sa pagsamba sa mga anghel')]),
        choose([2], [3], T('الرسل جميعهم:', 'All the messengers were:', 'Ang lahat ng mga sugo ay:'),
               [T('بشر عبيد لله، صادقون مصدَّقون', 'humans, servants of Allah, honest and trusted',
                  'mga tao lamang na tagapaglingkod ng Allah, makatotohanan at pinatotohanan'),
                T('ليسوا من البشر', 'not human beings', 'hindi mga tao'), T('ملائكة في صورة بشر', 'Angels in human form', 'Mga anghel na nasa anyong tao')]),
        choose([2], [3], T('هل بلّغ الرسل جميع ما أرسلهم الله به؟', 'Did the messengers convey all that Allah sent them with?',
                           'Ipinaabot ba ng mga sugo ang lahat ng iniutos ng Allah sa kanila?'),
               [T('نعم، بلّغوه جميعًا', 'Yes, they conveyed all of it', 'Oo, ipinaabot nila ang lahat ng ito'),
                T('بلّغوا بعضه وكتموا بعضه', 'They conveyed some of it and hid some', 'Ipinaabot nila ang ilan at itinago ang iba'), T('لم يبلّغوا شيئًا', 'They conveyed nothing', 'Wala silang ipinarating')]),
        choose([3], [4], T('ما أصل الدين الذي اتفقت عليه دعوة الرسل؟', 'What is the principle of religion that all the messengers called to?',
                           'Ano ang pundasyon ng pananampalataya na ipinanawagan ng lahat ng mga sugo?'),
               [T('توحيد الله في العبادة وعدم الإشراك به', 'Worshipping Allah alone without associating partners with Him',
                  'Ang kaisahan ng Allah sa pagsamba at paglayo sa pagtatambal sa Kanya'),
                T('اختلفت دعوتهم في أصل الدين', 'They differed on the principle of religion', 'Nagkaiba-iba sila sa pundasyon ng pananampalataya'), T('كثرة العبادات دون توحيد', 'Many acts of worship without tawhid', 'Maraming pagsamba nang walang tawhid')]),
        choose([4], [6, 5], T('مما يتعلق باليوم الآخر:', 'Among the things related to the Last Day:', 'Kabilang sa mga may kaugnayan sa Huling Araw:'),
               [T('البعث والميزان والحساب والجنة والنار', 'Resurrection, the Scale, reckoning, Paradise and Hell',
                  'Ang pagbangon muli, ang timbangan, ang paglilitis, ang Paraiso at ang Impiyerno'),
                T('بعث رسول إلى كل أمة', 'Sending a messenger to every nation', 'Ang pagpapadala ng Sugo sa bawat sambayanan'), T('الأعمال اليومية في الدنيا', 'Daily work in this world', 'Ang pang-araw-araw na gawain sa mundong ito')]),
        choose([4], [6], T('الإيمان باليوم الآخر هو التصديق الجازم بكل ما يتعلق به مما:',
                           'Belief in the Last Day is firm belief in everything about it that:',
                           'Ang paniniwala sa Huling Araw ay paniniwala sa lahat ng tungkol dito na:'),
               [T('أخبر به ربنا في كتابه، أو حدّثنا عنه نبينا محمد ﷺ', 'our Lord mentions in the Qur’an or Prophet Muhammad told us',
                  'ibinalita sa atin ng Allah sa Kanyang aklat at sinabi sa atin ng Propeta Muhammad ﷺ'),
                T('لم يخبر به الله ولا رسوله', 'neither Allah nor His Messenger told us', 'hindi ibinalita ng Allah o ng Kanyang Sugo'), T('اتفق عليه الناس', 'Whatever people agreed on', 'Anumang napagkasunduan ng mga tao')]),
    ],
    notes='Pillars 4 and 5. The Filipino list of Last-Day matters adds items not in the Arabic (blessing and '
          'punishment in the grave, the gathering); exercises use only items present in all three languages.',
)

u4l4 = L(
    'u4-l4', T('القدر خيره وشره', 'Predestination, the Good and Bad of It', 'Ang Qadar, Mabuti man o Masama'),
    {'site_section': 'أتعرف على أركان الإيمان › الركن السادس (tab6_6)', 'steps': None, 'page_ar': '57–58'},
    {'ar': [(107, 114)], 'en': [(107, 114)], 'tl': [(168, 180)]},
    [
        C('text', 'iman pillar 6', ar=[107, S(108, None, 'قال تعالى:')], en=[107, S(108, None, 'Allah Almighty says:')],
          tl=[168, 169, S(170, None, 'Sinabi ng Allah:')], q=(54, 49, 49)),
        C('text', 'iman pillar 6', ar=[109], en=[109], tl=[171]),
        C('text', 'iman pillar 6', ar=[110, 111, 112, 113, 114], en=[110, 111, 112, 113, 114],
          tl=[172, 173, J(174), 175, J(S(176, drop=[' sa “lawhul mahfudh”'])), 177, J(178), 179, J(180)]),
    ],
    [
        O(T('يعرف معنى الإيمان بالقدر: أن كل ما يقع بعلم الله وقدره، وأن الأقدار مكتوبة قبل خلق الإنسان',
            'Knows what belief in predestination means: everything happens by Allah’s knowledge and decree, written before mankind was created',
            'Alam ang kahulugan ng paniniwala sa Qadar: lahat ay itinakda ng Allah at nakasulat bago pa likhain ang tao'),
          [2, 1], key=True),
        O(T('يعرف أن للإنسان إرادة ومشيئة، وأن ذلك لا يخرج عن علم الله ومشيئته',
            'Knows that a person has a will and choice, and that this is not beyond Allah’s knowledge and will',
            'Alam na ang tao ay may sariling kagustuhan, ngunit hindi ito lalabas sa kaalaman at kagustuhan ng Allah'), [2]),
        O(T('يرتّب مراتب الإيمان بالقدر الأربع', 'Puts the four levels of belief in predestination in order',
            'Naisasaayos ang apat na antas ng paniniwala sa Qadar'), [3], key=True),
    ],
    [
        order([3], [3], T('رتّب مراتب الإيمان بالقدر', 'Put the levels of belief in predestination in order',
                          'Isaayos ang mga antas ng paniniwala sa Qadar'),
              [T('العلم', 'Allah’s knowledge', 'Ang kaalaman ng Allah'),
               T('الكتابة', 'Allah’s writing of all that will be', 'Ang pagsulat ng Allah'),
               T('المشيئة والقدرة', 'Allah’s will and omnipotence', 'Ang kagustuhan at kapangyarihan ng Allah'),
               T('الخلق', 'Allah as Creator of everything', 'Ang Allah ang Tagapaglikha')]),
        match([3], [3], T('صِل كل مرتبة بمعناها', 'Match each level with its meaning', 'Itugma ang bawat antas sa kahulugan nito'),
              [(T('الأولى', 'First', 'Una'), T('الإيمان بعلم الله الشامل المحيط', 'Belief in Allah’s knowledge that encompasses everything',
                                                'Paniniwala sa pangmalawakang kaalaman ng Allah')),
               (T('الثانية', 'Second', 'Ikalawa'), T('الإيمان بكتابة الله لكل ما هو كائن إلى يوم القيامة',
                                                   'Belief that Allah wrote all that will exist until the Day of Judgment',
                                                   'Paniniwala sa pagsulat ng Allah ng lahat ng mangyayari hanggang sa Araw ng Paghuhukom')),
               (T('الثالثة', 'Third', 'Ikatlo'), T('الإيمان بمشيئة الله النافذة وقدرته التامة', 'Belief in Allah’s executive Will and His Omnipotence',
                                                  'Paniniwala sa kagustuhan ng Allah at Kanyang buong kapangyarihan')),
               (T('الرابعة', 'Fourth', 'Ikaapat'), T('الإيمان بأن الله خالق كل شيء', 'Belief that Allah is the Creator of everything',
                                                    'Paniniwala na ang Allah ang Tagapaglikha ng lahat ng bagay'))]),
        choose([1], [2, 1], T('متى كُتبت الأقدار؟', 'When were the predestinations written?', 'Kailan isinulat ang mga pagtatakda?'),
               [T('قبل خلق الإنسان', 'Before the creation of mankind', 'Bago pa man likhain ang tao'),
                T('بعد وقوع الأحداث', 'After the events happen', 'Pagkatapos mangyari ang mga bagay'), T('لم تُكتب أبدًا', 'They were never written', 'Hindi kailanman isinulat ang mga ito')]),
        choose([2], [2], T('هل للإنسان إرادة ومشيئة؟', 'Does a person have a will and choice?', 'May sariling kagustuhan ba ang tao?'),
               [T('نعم، وهو فاعل لأفعاله حقيقة، ولا يخرج ذلك عن علم الله ومشيئته',
                  'Yes; he is the real doer of his actions, and this is not beyond Allah’s knowledge and will',
                  'Oo; siya ang totoong gumagawa nito, ngunit hindi ito lalabas sa kaalaman at kagustuhan ng Allah'),
                T('لا، ليس له إرادة ولا مشيئة', 'No, he has no will or choice', 'Wala, wala siyang sariling kagustuhan'), T('له إرادة تخرج عن مشيئة الله', 'He has a will outside Allah’s will', 'May kalooban siyang labas sa kalooban ni Allah')]),
        choose([1], [2], T('كل ما يقع على المخلوقات في هذه الدنيا هو:', 'Everything that happens to the creatures in this world is:',
                           'Ang lahat ng nangyayari sa mga nilikha sa mundong ito ay:'),
               [T('بعلم الله وقدره وتدبيره وحده', 'by the knowledge and predestination of Allah alone', 'itinakda ng Allah'),
                T('خارج عن علم الله', 'beyond Allah’s knowledge', 'labas sa kaalaman ng Allah'), T('مصادفة لا تدبير فيها', 'Chance with no planning', 'Nagkataon lamang nang walang pangangasiwa')]),
        choose([2], [2], T('أفعال الإنسان:', 'A person’s actions:', 'Ang mga gawa ng tao:'),
               [T('يفعلها حقيقة، وهي لا تخرج عن علم الله وإرادته ومشيئته', 'are truly his, and are not beyond Allah’s knowledge and will',
                  'ay talagang kanya, ngunit hindi lumalabas sa kaalaman at kagustuhan ng Allah'),
                T('تخرج عن علم الله ومشيئته', 'are beyond Allah’s knowledge and will', 'ay labas sa kaalaman at kagustuhan ng Allah'), T('لا يفعلها هو، بل تقع عليه بلا إرادة', 'He does not do them; they happen to him without his will', 'Hindi siya ang gumagawa; nangyayari lamang sa kanya nang walang kalooban')]),
    ],
    notes='Sixth pillar. Filipino card 3: the Arabic phrase "lawhul mahfudh" in Latin letters was dropped from the '
          'second level; the sentence still reads "the belief that Allah wrote all that will happen".',
)

LESSONS = [u4l1, u4l2, u4l3, u4l4]
