"""Unit 3 — أركان الإسلام (LRN-09). Line numbers: ar/en = spreadsheet rows, tl = site lines."""
from build import S, J, D, Q, X, C, O, L, T, choose, order, match

u3l1 = L(
    'u3-l1', T('أركان الإسلام الخمسة', 'The Five Pillars of Islam', 'Ang Limang Haligi ng Islam'),
    {'site_section': 'أتعرف على أركان الإسلام (intro) + الركن الأول (review)', 'steps': None, 'page_ar': '27–31'},
    {'ar': [(47, 49)], 'en': [(47, 49)], 'tl': [(71, 73)]},
    [
        C('text', 'pillars intro', ar=[47], en=[47], tl=[71]),
        C('text', 'pillars intro', ar=[48, 49], en=[48, 49], tl=[72, 73]),
        C('review', 'pillar 1 (review of u1-l1)', ar=[50, 52, 53], en=[50, 52, 53],
          tl=[77, 78, S(81, drop=[' ng ‘’la ilaha illa Allah’’']), 82]),
    ],
    [
        O(T('يعدّد أركان الإسلام الخمسة بترتيبها', 'Lists the five pillars of Islam in order',
            'Naiisa-isa ang limang haligi ng Islam ayon sa pagkakasunod'), [1], key=True),
        O(T('يعرف أن أركان الإسلام تلزم كل مسلم، ولماذا سُمّيت أركانًا', 'Knows that the pillars of Islam are required of every Muslim, and why they are called pillars',
            'Alam na ang mga haligi ng Islam ay dapat gampanan ng bawat Muslim, at kung bakit tinawag itong mga haligi'),
          [2], key=True),
    ],
    [
        order([1], [1], T('رتّب أركان الإسلام كما في الحديث', 'Put the pillars of Islam in the order of the hadith',
                          'Isaayos ang mga haligi ng Islam ayon sa hadith'),
              [T('الشهادتان', 'The testimony of faith', 'Ang pagsasaksi'),
               T('إقام الصلاة', 'Establishing prayer', 'Ang pagdarasal (Salah)'),
               T('إيتاء الزكاة', 'Giving Zakah', 'Ang pagbibigay ng Zakah'),
               T('صوم رمضان', 'Fasting the month of Ramadan', 'Ang pag-aayuno sa buwan ng Ramadhan'),
               T('حج البيت', 'Pilgrimage to the House (Hajj)', 'Ang Hajj sa Makkah')]),
        choose([1], [1], T('على كم بُني الإسلام؟', 'On how many pillars is Islam built?', 'Sa ilang haligi itinayo ang Islam?'),
               [T('على خمس', 'Five', 'Lima'), T('على ثلاث', 'Three', 'Tatlo'), T('على ست', 'Six', 'Anim')]),
        choose([2], [2], T('لماذا سُمّيت أركان الإسلام بهذا الاسم؟', 'Why are they called the pillars of Islam?',
                           'Bakit tinawag itong mga haligi ng Islam?'),
               [T('لأن الإسلام مبنيّ عليها', 'Because Islam is built on them', 'Sapagka’t dito naitayo ang Islam'),
                T('لأنها لا تلزم المسلم', 'Because a Muslim does not have to do them', 'Sapagka’t hindi ito kailangang gawin ng Muslim'), T('لأنها من الآداب المستحبة فقط', 'Because they are only recommended manners', 'Dahil ang mga ito ay mabubuting asal lamang na hindi obligado')]),
        choose([2], [2], T('أركان الإسلام:', 'The pillars of Islam:', 'Ang mga haligi ng Islam:'),
               [T('تلزم كل مسلم، ولا يصح إسلامه إلا باعتقاد وجوبها والإتيان بها جميعًا',
                  'are required of every Muslim, who must observe all of them and believe they are obligatory',
                  'ay dapat gampanan ng bawat Muslim; kailangang paniwalaan at itaguyod ang lahat ng ito'),
                T('يكفي المسلم أن يأتي ببعضها', 'it is enough for a Muslim to do some of them',
                  'sapat na sa Muslim ang gawin ang ilan lamang sa mga ito'), T('تلزم العلماء وحدهم', 'They are required of scholars only', 'Obligado lamang ang mga ito sa mga iskolar')]),
        match(['u1-l1-o1', 'u1-l1-o2'], [3], T('مراجعة: صِل كل شهادة بمعناها', 'Review: match each testimony with its meaning',
                                              'Balik-aral: itugma ang bawat pagsaksi sa kahulugan nito'),
              [(T('شهادة أن لا إله إلا الله', 'The testimony that there is no god but Allah', 'Ang pagsaksi na walang diyos maliban sa Allah'),
                T('لا معبود حق إلا الله', 'There is no deity worthy of worship except Allah',
                  'Walang ibang diyos na karapat-dapat sambahin maliban sa Allah')),
               (T('شهادة أن محمدًا رسول الله', 'The testimony that Muhammad is the Messenger of Allah',
                  'Ang pagsaksi na si Muhammad ay Sugo ng Allah'),
                T('طاعته فيما أمر، وتصديقه فيما أخبر', 'Obeying his orders and believing what he related',
                  'Ang pagsunod sa kanyang utos at paniniwala sa kanyang ibinalita'))]),
    ],
    notes='Intro of «أتعرف على أركان الإسلام» plus one review card for the first pillar, already taught in u1-l1 '
          '(LRN-09 rule 3): the review card repeats the pillar title and the two meaning sentences; its one exercise '
          '(e5) counts toward the u1-l1 objectives. The two verses of the first pillar are not repeated here.',
)

u3l2 = L(
    'u3-l2', T('الصلاة والزكاة', 'Prayer and Zakah', 'Ang Salah at ang Zakah'),
    {'site_section': 'أتعرف على أركان الإسلام › الركن الثاني والثالث (tab5_2, tab5_3)', 'steps': None, 'page_ar': '32–36'},
    {'ar': [(54, 65)], 'en': [(54, 65)], 'tl': [(84, 97)]},
    [
        C('text', 'pillar 2', ar=[54, S(55, None, 'قال تعالى:')], en=[54, S(55, None, 'Allah Almighty says:')],
          tl=[84, 85, S(86, None, 'Sinabi ng Allah:')], q=(2, 110, 110)),
        C('text', 'pillar 2', ar=[56], en=[56], tl=[87]),
        C('text', 'pillar 3', ar=[57, S(58, None, 'قال تعالى:')], en=[57, S(58, None, 'Allah Almighty says:')],
          tl=[89, 90, S(91, None, 'Sinabi ng Allah:')], q=(2, 110, 110)),
        C('text', 'pillar 3', ar=[59, 60], en=[59, 60], tl=[92, S(93, None, 'karapat-dapat bigyan nito.')]),
        C('text', 'pillar 3', ar=[61], en=[61], tl=[S(93, 'Ito ay obligado')]),
        C('text', 'pillar 3', ar=[62], en=[62], tl=[94]),
        C('text', 'pillar 3', ar=[63, 64, 65], en=[63, 64, 65], tl=[95, 96, 97]),
    ],
    [
        O(T('يعرف أن إقامة الصلاة أداؤها على الوجه الذي شرعه الله وعلّمه رسوله ﷺ',
            'Knows that establishing prayer means performing it as Allah prescribed and His Messenger ﷺ taught',
            'Alam na ang pagtataguyod ng Salah ay pagsasagawa nito ayon sa isinabatas ng Allah at itinuro ng Kanyang Sugo ﷺ'),
          [1, 2], key=True),
        O(T('يعرف لماذا فرض الله الزكاة ولمن تُعطى، وما في أدائها من خير',
            'Knows why Allah made Zakah obligatory, to whom it is given, and the good in giving it',
            'Alam kung bakit inobliga ng Allah ang Zakah, kanino ito ibinibigay, at ang kabutihan sa pagbibigay nito'), [3, 4, 5, 6]),
        O(T('يعرف مقدار زكاة المال المدّخر ومتى تجب', 'Knows the amount of Zakah on saved wealth and when it is due',
            'Alam ang sukat ng Zakah sa naipong kayamanan at kung kailan ito obligado'), [7], key=True),
    ],
    [
        choose([1], [2, 1], T('إقامة الصلاة تكون:', 'Establishing prayer means:', 'Ang pagtataguyod ng Salah ay:'),
               [T('بأدائها على الوجه الذي شرعه الله وعلّمه لنا رسوله محمد ﷺ',
                  'performing it in the way prescribed by Allah and taught to us by His Messenger Muhammad ﷺ',
                  'pagsasagawa nito sa paraang isinabatas ng Allah at itinuro sa atin ng Kanyang Sugo ﷺ'),
                T('بأدائها بأي طريقة يختارها المسلم', 'performing it in any way the Muslim chooses',
                  'pagsasagawa nito sa anumang paraang gusto ng Muslim'), T('بالقراءة عنها دون أدائها', 'By reading about it without performing it', 'Sa pagbabasa tungkol dito nang hindi ito isinasagawa')]),
        match([1, 2], [1, 3, 5], T('صِل كل عبارة بما يناسبها', 'Match each phrase with what fits it',
                                   'Itugma ang bawat parirala sa angkop dito'),
              [(T('إقام الصلاة', 'Establishing prayer', 'Ang pagsagawa ng Salah'),
                T('الركن الثاني', 'the second pillar', 'ang ikalawang haligi')),
               (T('إيتاء الزكاة', 'Giving Zakah', 'Ang pagbibigay ng Zakah'),
                T('الركن الثالث', 'the third pillar', 'ang ikatlong haligi')),
               (T('مستحقو الزكاة', 'Those eligible for Zakah', 'Ang mga karapat-dapat sa Zakah'),
                T('أصناف ثمانية ذكرهم الله في القرآن، منهم الفقير والمسكين',
                  'eight categories mentioned in the Qur’an, including the poor and needy',
                  'walong uri ng tao na binanggit sa Qur’an, kabilang ang mga dukha at mahihirap'))]),
        choose([2], [4], T('من أسباب فرض الزكاة:', 'One reason Allah made zakah obligatory:', 'Isa sa mga dahilan kung bakit inobliga ni Allah ang zakah:'),
               [T('إعانة الفقراء والمحتاجين', 'to help the poor and needy', 'upang tulungan ang mga mahihirap at nangangailangan'),
                T('مرور سنة كاملة', 'the passing of a full year', 'ang paglipas ng isang buong taon'),
                T('الذهب والفضة', 'gold and silver', 'ginto at pilak')]),
        choose([2], [4, 5], T('لمن تُعطى الزكاة؟', 'To whom is Zakah given?', 'Kanino ibinibigay ang Zakah?'),
               [T('للمستحقين، وهم أصناف ثمانية ذكرهم الله في القرآن', 'to those eligible: eight categories mentioned in the Qur’an',
                  'sa mga karapat-dapat: walong uri ng tao na binanggit sa Qur’an'),
                T('لأي أحد ولو لم يكن من المستحقين', 'to anyone, even if not eligible', 'kahit kanino, kahit hindi karapat-dapat'), T('للأغنياء', 'To the rich', 'Sa mayayaman')]),
        choose([2], [6], T('في أداء الزكاة:', 'Giving Zakah:', 'Ang pagbibigay ng Zakah ay:'),
               [T('تطهير لأخلاق المسلم وأمواله، وتقوية للمحبة بين أفراد المجتمع',
                  'purifies the Muslim’s character and wealth, and strengthens love in the community',
                  'nagdadalisay sa kayamanan at pag-uugali ng Muslim, at nagpapalakas ng pagmamahalan sa lipunan'),
                T('إضعاف للمحبة بين أفراد المجتمع', 'weakens the love between people in the community',
                  'nagpapahina ng pagmamahalan sa lipunan'), T('لا خير فيه للمجتمع', 'No good for society', 'Walang kabutihan para sa lipunan')]),
        choose([3], [7], T('كم مقدار زكاة المال المدّخر؟', 'What is the amount of Zakah on saved wealth?',
                           'Gaano kalaki ang Zakah sa naipong kayamanan?'),
               [T('2.5%', '2.5%', '2.5%'), T('25%', '25%', '25%'), T('50%', '50%', '50%')]),
        choose([3], [7], T('متى تجب زكاة المال المدّخر؟', 'When is Zakah due on saved wealth?',
                           'Kailan nagiging obligado ang Zakah sa naipong kayamanan?'),
               [T('إذا بلغت قيمته مقدارًا معينًا ومرّت عليه سنة كاملة', 'when it reaches a certain amount and a full year has passed',
                  'kapag umabot ito sa tamang sukat at lumipas ang isang buong taon'),
                T('كلما ربح ولو لم تمرّ عليه سنة', 'whenever there is profit, even before a year has passed',
                  'tuwing may kita, kahit hindi pa lumilipas ang isang taon'), T('مرة واحدة في العمر', 'Once in a lifetime', 'Isang beses lamang sa buong buhay')]),
    ],
    notes='Pillars 2 and 3. Verse Al-Baqarah 2:110 is quoted for both pillars (one quran field each). The English '
          'livestock list omits cattle and the Filipino text says "more than a year" for grazing; exercises avoid '
          'the livestock and produce sentences (reviewer).',
)

u3l3 = L(
    'u3-l3', T('الصوم والحج', 'Fasting and Hajj', 'Ang Pag-aayuno at ang Hajj'),
    {'site_section': 'أتعرف على أركان الإسلام › الركن الرابع والخامس (tab5_4, tab5_5)', 'steps': None, 'page_ar': '37–40'},
    {'ar': [(66, 71)], 'en': [(66, 71)], 'tl': [(99, 108)]},
    [
        C('text', 'pillar 4', ar=[66, S(67, None, 'قال تعالى:')], en=[66, S(67, None, 'Allah Almighty says:')],
          tl=[99, 100, S(101, None, 'Sinabi ng Allah:')], q=(2, 183, 183)),
        C('text', 'pillar 4', ar=[68], en=[68], tl=[102]),
        C('text', 'pillar 4', ar=[69], en=[69], tl=[103]),
        C('text', 'pillar 5', ar=[70, S(71, None, 'قال تعالى:')], en=[70, S(71, None, 'Allah Almighty says:')],
          tl=[105, 106, S(107, None, 'Sinabi ng Allah:')], q=(3, 97, 97)),
        C('text', 'pillar 5', ar=[S(71, 'الحج يكون', 'فقال:')], en=[S(71, 'Hajj is obligatory', "the noble Qur'an:")],
          tl=[S(108, None, 'Maluwalhating Qur’an:')], q=(22, 27, 27)),
    ],
    [
        O(T('يعرف أن رمضان الشهر التاسع من التقويم الهجري، وأن صيامه كاملًا أحد أركان الإسلام',
            'Knows that Ramadan is the ninth month of the Hijri calendar and that fasting all of it is a pillar of Islam',
            'Alam na ang Ramadhan ay ika-siyam na buwan ng Hijri at ang pag-aayuno rito ay haligi ng Islam'), [1, 2], key=True),
        O(T('يعرف معنى صوم رمضان ووقته من الفجر إلى غروب الشمس', 'Knows what fasting Ramadan is, from dawn to sunset',
            'Alam ang kahulugan ng pag-aayuno sa Ramadhan, mula Fajr hanggang paglubog ng araw'), [3], key=True),
        O(T('يعرف أن الحج على المستطيع مرة واحدة في العمر', 'Knows that Hajj is due once in a lifetime on whoever is able',
            'Alam na ang Hajj ay obligado nang isang beses sa buhay sa sinumang may kakayahan'), [4, 5]),
    ],
    [
        choose([1], [2, 1], T('رمضان هو الشهر … من التقويم الهجري', 'Ramadan is the … month of the Hijri calendar',
                              'Ang Ramadhan ay ang … na buwan ng Hijri'),
               [T('التاسع', 'ninth', 'ika-siyam'), T('الأول', 'first', 'unang'), T('الثاني عشر', 'twelfth', 'ika-labindalawang')]),
        choose([1], [2], T('صيام رمضان كاملًا:', 'Fasting the whole month of Ramadan:', 'Ang pag-aayuno sa buwan ng Ramadhan:'),
               [T('أحد أركان الإسلام الخمسة', 'is one of the five pillars of Islam', 'ay kabilang sa mga haligi ng Islam'),
                T('ليس من أركان الإسلام', 'is not one of the pillars of Islam', 'ay hindi kabilang sa mga haligi ng Islam'), T('مستحبّ لمن شاء', 'Recommended for whoever wishes', 'Mabuti lamang para sa may nais')]),
        choose([2], [3], T('يكون الصوم:', 'The fast lasts:', 'Ang pag-aayuno ay:'),
               [T('من طلوع الفجر إلى غروب الشمس', 'from dawn to sunset', 'mula sa pagsapit ng Fajr hanggang sa paglubog ng araw'),
                T('من غروب الشمس إلى طلوع الفجر', 'from sunset to dawn', 'mula sa paglubog ng araw hanggang sa Fajr'), T('طوال اليوم والليلة', 'All day and all night', 'Buong araw at buong gabi')]),
        match([2, 3, 1], [3, 5, 2], T('صِل كل وصف بما يناسبه', 'Match each description with what it describes',
                                      'Itugma ang bawat paglalarawan sa tinutukoy nito'),
              [(T('الإمساك عن الطعام والشراب والجماع من الفجر إلى غروب الشمس', 'Abstaining from eating, drinking and intercourse from dawn to sunset',
                  'Pag-iwas sa pagkain, inumin at pakikipagtalik mula Fajr hanggang paglubog ng araw'),
                T('صوم رمضان', 'Fasting Ramadan', 'Pag-aayuno sa Ramadhan')),
               (T('قصد البيت الحرام والمشاعر المقدسة بمكة لأداء عبادات معينة', 'Going to the Sacred House and holy places in Makkah for certain acts of worship',
                  'Pagtungo sa Makkah at sa mga banal na lugar upang isagawa ang mga natatanging pagsamba'),
                T('الحج', 'Hajj', 'Hajj')),
               (T('الشهر التاسع من التقويم الهجري', 'The ninth month of the Hijri calendar', 'Ika-siyam na buwan ng Hijri'),
                T('رمضان', 'Ramadan', 'Ramadhan'))]),
        choose([3], [5, 4], T('كم مرة يجب الحج على مَن استطاع؟', 'How often is Hajj due on whoever is able?',
                              'Ilang beses obligado ang Hajj sa may kakayahan?'),
               [T('مرة واحدة في العمر', 'Once in a lifetime', 'Isang beses sa buhay'),
                T('كل سنة', 'Every year', 'Bawat taon'), T('كل عشر سنين', 'Every ten years', 'Bawat sampung taon')]),
        choose([3], [5], T('هل حجّ الأنبياءُ البيتَ؟', 'Did the prophets perform Hajj to the House?', 'Nagsagawa ba ng Hajj ang mga propeta?'),
               [T('النبي ﷺ وغيره من الأنبياء من قبله', 'The Prophet ﷺ, and other prophets before him',
                  'Ang Propeta ﷺ at ang iba pang mga propeta na nauna sa kanya'),
                T('لم يحجّ أحد من الأنبياء', 'None of the prophets performed Hajj', 'Walang propeta na nagsagawa ng Hajj'), T('حجّ النبي ﷺ وحده', 'Only the Prophet (peace be upon him)', 'Ang Propeta lamang')]),
    ],
    notes='Pillars 4 and 5. The fasting verse is Al-Baqarah 2:183; the spreadsheet (Arabic and English) and the '
          'Filipino page cite it as "2:110" — the quran field uses 2:183 (as on the Arabic site). The English '
          'spreadsheet definition of fasting omits "and other things that break the fast"; exercises use only '
          'eating, drinking and intercourse, which all three languages state.',
)

LESSONS = [u3l1, u3l2, u3l3]
