"""Unit 6 — أخلاقي وسعادتي (LRN-09). Line numbers: ar/en = spreadsheet rows, tl = site lines."""
from build import S, J, D, Q, X, C, O, L, T, choose, order, match

TITLE = 'repeats the section title (shown as the lesson title)'

u6l1 = L(
    'u6-l1', T('حجاب المرأة المسلمة', 'The Hijab of the Muslim Woman', 'Ang Hijab ng Babaeng Muslim'),
    {'site_section': 'حجاب المرأة المسلمة', 'steps': None, 'page_ar': '109–111'},
    {'ar': [(215, 223)], 'en': [(215, 223)], 'tl': [(422, 438)]},
    [
        C('text', 'hijab', ar=[S(215, None, 'قال تعالى:')], en=[S(215, None, 'Allah Almighty says:')],
          tl=[S(422, None, 'Sinabi ng Allah:')], q=(33, 59, 59)),
        C('text', 'hijab', ar=[S(215, 'أوجب الله')], en=[S(215, 'Allah has commanded')], tl=[423]),
        C('text', 'rules of dress', ar=[216, 217, 218, 219, 220, 221, 222, 223], en=[216, 217, 218, 219, 220, 221, 222, 223],
          tl=[424, 425, J(426), 427, J(428), 429, J(430), 431, J(432), 433, J(434), 435, J(436), 437, J(438)]),
    ],
    [
        O(T('يعرف أن الله أوجب على المرأة المسلمة الحجاب وستر بدنها عن الرجال الأجانب',
            'Knows that Allah commanded the Muslim woman to wear the hijab and cover her body from men not related to her',
            'Alam na inutusan ng Allah ang babaeng Muslim na magsuot ng Hijab at takpan ang kanyang awra mula sa mga lalaking hindi kaanu-ano'),
          [2, 1], key=True),
        O(T('يعرف أمام مَن تخلع المرأة حجابها، ومَن هم المحارم', 'Knows before whom a woman may take off her hijab, and who her mahram are',
            'Alam kung kanino maaaring alisin ng babae ang Hijab, at kung sino ang mga Mahram'), [2]),
        O(T('يعدّد ضوابط لباس المرأة المسلمة', 'Lists the rules for the Muslim woman’s dress', 'Naiisa-isa ang mga panuntunan sa pananamit ng babaeng Muslim'),
          [3], key=True),
    ],
    [
        choose([1], [2, 1], T('عمّن تستر المرأة المسلمة بدنها بالحجاب؟', 'From whom does the Muslim woman cover her body with the hijab?',
                              'Mula kanino tinatakpan ng babaeng Muslim ang kanyang awra?'),
               [T('عن الرجال الأجانب عنها', 'From men who are not directly related to her', 'Mula sa mga lalaking hindi direktang kaugnay niya'),
                T('عن زوجها', 'From her husband', 'Mula sa kanyang asawa'), T('لا تستره عن أحد', 'From no one', 'Hindi sa sinuman')]),
        choose([2], [2], T('أمام مَن يجوز للمرأة أن تخلع حجابها؟', 'Before whom may a woman take off her hijab?',
                           'Sa harap nino maaaring alisin ng babae ang kanyang Hijab?'),
               [T('أمام زوجها أو محارمها', 'Before her husband or her mahram', 'Sa harap ng kanyang asawa o mga Mahram'),
                T('أمام الرجال الأجانب عنها', 'Before men not related to her', 'Sa harap ng mga lalaking hindi kaanu-ano'), T('أمام كل من تعرفه', 'In front of anyone she knows', 'Sa harap ng sinumang kakilala niya')]),
        choose([2], [2], T('المحارم هم:', 'The mahram are:', 'Ang mga Mahram ay:'),
               [T('الذين لا يجوز للمرأة المسلمة الزواج بهم بشكل مؤبد', 'the men she is permanently forbidden to marry',
                  'ang mga taong hindi kailanman maaaring pakasalan ng babaeng Muslim'),
                T('الرجال الأجانب عنها', 'men who are not related to her', 'mga lalaking hindi kaanu-ano'), T('كل الأقارب ولو جاز لها الزواج بهم', 'All relatives, even those she may marry', 'Lahat ng kamag-anak, kahit yaong maaari niyang pakasalan')]),
        choose([1], [2, 3], T('بأي لباس تستر المرأة المسلمة بدنها؟', 'With what clothing does the Muslim woman cover her body?',
                              'Sa anong kasuotan tinatakpan ng babaeng Muslim ang kanyang katawan?'),
               [T('باللباس المعتاد في بلادها', 'With the traditional outfits of her country', 'Sa tradisyonal na kasuotan sa kanyang bansa'),
                T('بلباس الرجل', 'With men’s clothing', 'Sa kasuotan ng kalalakihan'), T('بلباس شفاف', 'With see-through clothing', 'Gamit ang manipis na damit na nakikita ang katawan')]),
        choose([3], [3], T('من ضوابط لباس المرأة المسلمة:', 'One of the rules for the Muslim woman’s dress:',
                           'Isa sa mga panuntunan sa pananamit ng babaeng Muslim:'),
               [T('أن يستوعب جميع البدن، وألّا يكون معطرًا', 'It must cover the whole body and must not be perfumed',
                  'Sinasaklaw nito ang buong katawan at hindi ito dapat lagyan ng pabango'),
                T('أن يكون شفافًا يُظهر البدن', 'It must be transparent, showing the body', 'Dapat itong manipis upang lumitaw ang katawan'), T('أن يكون ضيقًا يصف الجسم', 'That it is tight and shows the shape of the body', 'Na ito ay masikip at naglalarawan sa hugis ng katawan')]),
        choose([3], [3], T('هل يجوز أن يشبه لباسُ المرأة المسلمة لباسَ الرجل؟', 'May the Muslim woman’s dress resemble what men wear?',
                           'Maaari bang maging katulad ng kasuotan ng lalaki ang Hijab?'),
               [T('لا، من ضوابطه ألّا يشبه لباس الرجل', 'No — one rule is that it must not resemble what men wear',
                  'Hindi — isa sa mga panuntunan ay hindi ito dapat katulad ng kasuotan ng kalalakihan'),
                T('نعم', 'Yes', 'Oo'), T('نعم، إذا كان جميلًا', 'Yes, if it looks nice', 'Oo, kung ito ay maganda')]),
    ],
    notes='Section «حجاب المرأة المسلمة». The Filipino list repeats rule 3 ("not thin") as rule 4 and lacks the '
          'rule "loose, not tight"; no exercise asks about rule 4 (reviewer). The list of mahram is shown as the '
          'book gives it but not tested (details of family relations are left to the card).',
)

u6l2 = L(
    'u6-l2', T('من صفات المؤمن', 'Some Traits of the Believer', 'Ilan sa mga Katangian ng Mananampalataya'),
    {'site_section': 'من صفات المؤمن', 'steps': None, 'page_ar': '113–116'},
    {'ar': [(224, 247)], 'en': [(224, 247)], 'tl': [(441, 463)]},
    [
        C('text', 'believer', ar=[S(225, None, 'قال تعالى:')], en=[Q(225)], tl=[S(441, None, 'Sinabi ng Allah:')], q=(8, 2, 2)),
        C('text', 'traits 1-8', ar=[226, 227, 228, 229, 230, 231, 232, 233], en=[226, 227, 228, 229, 230, 231, 232, 233],
          tl=[442, 443, 444, 445, 446, 447, 448, 449]),
        C('text', 'traits 9-15', ar=[234, 235, 236, 237, 238, 239, 240], en=[234, 235, 236, 237, 238, 239, 240],
          tl=[450, 451, 452, 453, 454, 455, 456]),
        C('text', 'traits 16-22', ar=[241, 242, 243, 244, 245, 246, 247], en=[241, 242, 243, 244, 245, 246, 247],
          tl=[457, 458, 459, 460, 461, 462, 463]),
    ],
    [
        O(T('يذكر من صفات المؤمن في معاملة الناس: الصدق والوفاء بالعهد وأداء الأمانة وصلة الرحم',
            'Names traits of the believer in dealing with people: honesty, keeping promises, fulfilling trusts, kinship ties',
            'Nasasabi ang mga katangian ng mananampalataya sa pakikitungo sa tao: katapatan, pagtupad sa pangako, pag-iingat ng ipinagkatiwala, pagbisita sa kamag-anak'),
          [2, 1], key=True),
        O(T('يعرف حال قلب المؤمن مع قدر الله ومع الناس', 'Knows the state of the believer’s heart toward Allah’s decree and toward people',
            'Alam ang kalagayan ng puso ng mananampalataya sa tadhana ng Allah at sa kapwa'), [3]),
        O(T('يعرف ما يجتنبه المؤمن: الربا والزنا والخمر والظلم والسرقة', 'Knows what the believer avoids: usury, adultery, alcohol, oppression and theft',
            'Alam ang iniiwasan ng mananampalataya: Riba, pangangalunya, alak, pang-aapi at pagnanakaw'), [3, 4], key=True),
        O(T('يعرف حق الوالدين والجيران في الدرس', 'Knows what the lesson says about parents and neighbours',
            'Alam ang sinasabi ng aralin tungkol sa mga magulang at kapitbahay'), [4]),
    ],
    [
        choose([1], [2, 1], T('المؤمن في حديثه:', 'In his speech, the believer is:', 'Sa kanyang pananalita, ang mananampalataya ay:'),
               [T('صادق لا يكذب', 'honest and does not lie', 'matapat at hindi nagsisinungaling'),
                T('يكذب أحيانًا', 'sometimes lies', 'paminsan-minsang nagsisinungaling'), T('يكتم الحق', 'He hides the truth', 'Itinatago niya ang katotohanan')]),
        match([1], [2], T('صِل كل أمر بما يفعله المؤمن تجاهه', 'Match each thing with what the believer does with it',
                          'Itugma ang bawat bagay sa ginagawa ng mananampalataya rito'),
              [(T('العهد والوعد', 'Vows and promises', 'Mga pangako'), T('يفي بهما', 'he honors them', 'tinutupad niya')),
               (T('الأمانة', 'Trusts', 'Ang ipinagkatiwala sa kanya'), T('يؤديها', 'he fulfills them', 'ibinabalik niya')),
               (T('الرحم', 'Kinship ties', 'Mga kamag-anak'), T('يصلها', 'he upholds them', 'binibisita niya'))]),
        choose([2], [3], T('المؤمن في حال الرخاء وفي حال الضراء:', 'In times of prosperity and of adversity, the believer:',
                           'Sa panahon ng kasaganaan at ng kagipitan, ang mananampalataya ay:'),
               [T('يشكر الله في الرخاء، ويصبر في الضراء', 'is grateful to Allah in prosperity and patient in adversity',
                  'nagpapasalamat sa Allah sa kasaganaan at nagtitimpi sa kagipitan'),
                T('يسخط على قدر الله في الضراء', 'is angry at Allah’s decree in adversity', 'nagagalit sa tadhana ng Allah sa kagipitan'), T('يشكر في الرخاء ويسخط في الضراء', 'Grateful in ease, resentful in hardship', 'Nagpapasalamat sa ginhawa, nagagalit sa kahirapan')]),
        match([2, 3], [3], T('صِل كلًّا بحال المؤمن معه', 'Match each with how the believer deals with it', 'Itugma ang bawat isa sa pakikitungo ng mananampalataya rito'),
              [(T('قلب المؤمن', 'The believer’s heart', 'Ang puso ng mananampalataya'),
                T('سليم من الأحقاد', 'is free of grudges', 'ay malinis mula sa inggit at pagkamuhi')),
               (T('الربا', 'Usury', 'Ang Riba'), T('لا يأكله ولا يتعامل به', 'he avoids it', 'hindi siya kumakain mula rito')),
               (T('الناس', 'People', 'Ang mga tao'), T('يعفو عنهم', 'he forgives them', 'pinapatawad niya sila'))]),
        choose([3], [3, 4], T('مما يجتنبه المؤمن:', 'Among what the believer avoids:', 'Kabilang sa iniiwasan ng mananampalataya:'),
               [T('الربا، والزنا، وشرب الخمر', 'Usury, adultery and drinking alcohol', 'Riba, pangangalunya at pag-inom ng alak'),
                T('صلة الرحم، والإحسان إلى الجيران', 'Upholding kinship ties and treating neighbours well',
                  'Pagbisita sa kamag-anak at mabuting pakikitungo sa kapitbahay'), T('الصدق، والوفاء بالعهد', 'Truthfulness and keeping promises', 'Katapatan at pagtupad sa pangako')]),
        choose([4], [4], T('المؤمن مع والديه وإن كانا غير مسلمَين:', 'With his parents, even if they are not Muslims, the believer:',
                           'Sa kanyang mga magulang, kahit hindi sila Muslim, ang mananampalataya ay:'),
               [T('بارّ بهما، ويطيعهما في المعروف', 'is dutiful to them and obeys them in doing good',
                  'mabuti ang pakikitungo sa kanila at sumusunod sa kanilang mabubuting utos'),
                T('لا يبرّهما لأنهما غير مسلمَين', 'is not dutiful to them because they are not Muslims',
                  'hindi mabuti ang pakikitungo sa kanila dahil hindi sila Muslim'), T('يطيعهما في كل شيء ولو في معصية', 'He obeys them in everything, even in sin', 'Sinusunod niya sila sa lahat, kahit sa kasalanan')]),
        choose([4], [4], T('المؤمن مع جيرانه:', 'With his neighbours, the believer:', 'Sa kanyang mga kapitbahay, ang mananampalataya ay:'),
               [T('يحسن إليهم', 'treats them well', 'mabuti ang pakikitungo sa kanila'),
                T('يعتدي عليهم', 'harms them', 'nananakit sa kanila'), T('يقاطعهم', 'He cuts them off', 'Pinuputol niya ang ugnayan sa kanila')]),
        choose([3], [4], T('هل يسرق المؤمن أو يحتال؟', 'Does the believer steal or defraud?', 'Nagnanakaw o nandaraya ba ang mananampalataya?'),
               [T('لا يسرق ولا يحتال', 'He does not steal or defraud', 'Iniiwasan niya ang pagnanakaw at pandaraya'),
                T('نعم، إذا احتاج', 'Yes, if he is in need', 'Oo, kapag nangangailangan'), T('يسرق من غير المسلمين', 'He steals from non-Muslims', 'Nagnanakaw siya sa mga hindi Muslim')]),
    ],
    xdrops=[X('ar', 224, reason=TITLE), X('en', 224, reason=TITLE)],
    notes='Section «من صفات المؤمن». In the spreadsheet the English row for the verse (8:2) has no "Allah says:" '
          'lead-in, so the English text of card 1 is empty and the card shows only the verse. The traits are split '
          'into three cards in the same order in all three languages (22 traits each).',
)

u6l3 = L(
    'u6-l3', T('سعادتي في ديني (1)', 'My Happiness in My Religion (1)', 'Ang Aking Kaligayahan sa Aking Relihiyon (1)'),
    {'site_section': 'سعادتي في ديني الإسلام (first half)', 'steps': None, 'page_ar': '118–122'},
    {'ar': [(249, 252)], 'en': [(249, 252)], 'tl': [(466, 472)]},
    [
        C('text', 'happiness', ar=[S(249, None, 'قال تعالى:')], en=[S(249, None, 'Allah Almighty says:')],
          tl=[S(466, None, 'Sinabi ng Allah:')], q=(16, 97, 97)),
        C('text', 'happiness', ar=[S(249, 'من أعظم ما يدخل', 'كما قال سبحانه:')], en=[S(249, 'One of the most important', 'Allah says:')],
          tl=[S(467, None, 'katulad ng sinabi ng Allah:')], q=(2, 186, 186)),
        C('text', 'happiness', ar=[S(249, 'وأمرنا سبحانه', 'حيث قال عز وجل:')], en=[S(249, 'Allah commands us', 'Allah says:')],
          tl=[S(468, None, 'sinabi ng Allah:')], q=(40, 60, 60)),
        C('text', 'happiness', ar=[S(249, 'فالمسلم الصالح')], en=[S(249, 'A true Muslim')], tl=[469]),
        C('text', 'happiness', ar=[250], en=[250], tl=[470]),
        C('text', 'happiness', ar=[S(251, None, 'قال تعالى:')], en=[S(251, None, 'Allah says:')],
          tl=[S(471, None, 'Sinabi ng Allah:')], q=(2, 257, 257)),
        C('text', 'happiness', ar=[252], en=[252], tl=[472]),
    ],
    [
        O(T('يعرف أن من أعظم أسباب السعادة ارتباط المسلم المباشر بربه دون وسيط',
            'Knows that one of the greatest sources of happiness is the Muslim’s direct connection to his Lord, without a mediator',
            'Alam na isa sa pinakadakilang dahilan ng kaligayahan ang direktang koneksyon ng Muslim sa kanyang Panginoon, nang walang tagapamagitan'),
          [2, 3, 4], key=True),
        O(T('يعرف الحكمة من خلقنا: عبادة الله وحده', 'Knows why we were created: to worship Allah alone',
            'Alam kung bakit tayo nilikha: upang sambahin ang Allah lamang'), [5], key=True),
        O(T('يعرف أن الشريعة حفظت ضرورات الحياة الخمس', 'Knows that the Sharia preserves the five necessities of life',
            'Alam na pinapanatili ng Sharia ang limang pangangailangan ng buhay'), [5]),
        O(T('يعرف ما تبعثه رابطة المسلم بربه من طمأنينة وسعادة', 'Knows the reassurance and happiness that the bond with his Lord brings',
            'Alam ang kapanatagan at kaligayahang dulot ng ugnayan ng Muslim sa kanyang Panginoon'), [6, 7, 1]),
    ],
    [
        choose([1], [2], T('من أعظم ما يدخل السعادة في قلب المسلم:', 'One of the greatest things that brings joy to the Muslim’s heart:',
                           'Isa sa pinakadakilang nagdudulot ng kaligayahan sa puso ng Muslim:'),
               [T('ارتباطه المباشر بربه دون وسيط', 'his direct connection to his Lord without a mediator',
                  'ang direktang koneksyon sa kanyang Panginoon nang walang tagapamagitan'),
                T('اتخاذ وسيط بينه وبين ربه من الأحياء أو الأموات', 'taking a mediator between him and his Lord from the living or the dead',
                  'pagkakaroon ng tagapamagitan sa pagitan niya at ng kanyang Panginoon mula sa mga buhay o patay'), T('كثرة المال', 'Having much wealth', 'Pagkakaroon ng maraming kayamanan')]),
        choose([1], [3, 4], T('بماذا أمرنا الله سبحانه؟', 'What has Allah commanded us to do?', 'Ano ang iniutos sa atin ni Allah?'),
               [T('بدعائه، وجعله من أعظم العبادات', 'to call upon Him; He made supplication one of the great acts of worship',
                  'na manalangin sa Kanya; ginawa Niya itong isa sa pinakadakilang pagsamba'),
                T('بترك الدعاء', 'to give up supplication', 'na itigil ang pananalangin'), T('بأن ندعو غيره', 'To call upon others besides Him', 'Na manalangin sa iba bukod sa Kanya')]),
        choose([2], [5], T('لماذا أوجدنا الله في هذا الكون؟', 'Why did Allah create us in this universe?',
                           'Bakit tayo nilikha ng Allah sa mundong ito?'),
               [T('لعبادته وحده لا شريك له', 'to worship Him alone without any partner', 'upang sambahin lamang Siya nang walang katambal'),
                T('عبثًا بلا حكمة', 'in vain, without wisdom', 'nang walang kabuluhan'), T('للّهو واللعب', 'For amusement and play', 'Para sa libangan at laro')]),
        choose([3], [5], T('ضرورات الحياة التي حفظتها الشريعة:', 'The necessities of life that the Sharia preserves:',
                           'Ang mga pangangailangan ng buhay na pinapanatili ng Sharia:'),
               [T('الدين والنفس والعرض والعقل والمال', 'religion, life, honor, mind and property',
                  'relihiyon, sarili, karangalan, isipan at kayamanan'),
                T('الطمأنينة والراحة والسرور', 'reassurance, comfort and delight', 'kapanatagan, kaginhawaan at kasiyahan'), T('المال والجاه فقط', 'Wealth and status only', 'Kayamanan at katayuan lamang')]),
        choose([3, 2], [5], T('مَن عاش متبعًا للأوامر الشرعية مجتنبًا للمحرمات:', 'Whoever follows the Sharia commandments and avoids its prohibitions:',
                              'Sinuman ang namuhay alinsunod sa Sharia at umiwas sa ipinagbabawal:'),
               [T('حفظ هذه الضرورات وعاش سعيدًا مطمئنًا', 'preserves these necessities and lives a happy, peaceful life',
                  'napangalagaan ang mga pangangailangang ito at namumuhay nang masaya at payapa'),
                T('ضيّع هذه الضرورات', 'loses these necessities', 'nawawala sa kanya ang mga ito'), T('لا فرق بينه وبين غيره', 'Is no different from anyone else', 'Walang pagkakaiba sa iba')]),
        choose([4], [6, 1], T('ماذا تبعث رابطة المسلم بربه؟', 'What does the Muslim’s bond with his Lord bring?',
                              'Ano ang dulot ng ugnayan ng Muslim sa kanyang Panginoon?'),
               [T('الطمأنينة والراحة النفسية والأمان والسرور', 'reassurance, spiritual comfort, safety and delight',
                  'kapanatagan, kaginhawaan ng sarili, katiwasayan at kasiyahan'),
                T('ضرورات الحياة الخمس', 'the five necessities of life', 'ang limang pangangailangan ng buhay'), T('الحزن والقلق', 'Sadness and worry', 'Kalungkutan at pag-aalala')]),
        match([4, 1], [7, 4], T('صِل كل عبارة بما يتمّ معناها', 'Match each statement with what completes its meaning', 'Itugma ang bawat pahayag sa kukumpleto ng kahulugan nito'),
              [(T('هذه العلاقة العظيمة', 'This great relationship', 'Ang mahusay na ugnayan na ito'),
                T('حالة وجدانية تحمل على التنعّم بعبادة الرحمن', 'is a spiritual state that makes the Muslim feel bliss in worshiping Allah',
                  'ay isang estado na humahantong sa pagtamasa ng pagsamba sa Pinakamaawain')),
               (T('المسلم الصالح', 'A true Muslim', 'Ang matuwid na Muslim'),
                T('دائم الاحتياج إلى ربه، ودائم الدعاء بين يديه', 'is permanently in need of his Lord and always supplicates Him',
                  'ay palaging nangangailangan sa kanyang Panginoon at palaging nananalangin'))]),
    ],
    notes='First half of «سعادتي في ديني الإسلام» (LRN-09 rule 4), split at the paragraph boundary before «تلك الحلاوة». '
          'Verses 16:97, 2:186, 40:60 and 2:257 are shown from the Quran database; the cards end where each verse '
          'begins and resume after it. The Filipino page quotes 4:124 instead of 16:97 for the opening verse; the '
          'quran field follows the Arabic (16:97) for all languages (reviewer).',
)

u6l4 = L(
    'u6-l4', T('سعادتي في ديني (2)', 'My Happiness in My Religion (2)', 'Ang Aking Kaligayahan sa Aking Relihiyon (2)'),
    {'site_section': 'سعادتي في ديني الإسلام (second half)', 'steps': None, 'page_ar': '122–125'},
    {'ar': [(253, 257)], 'en': [(253, 257)], 'tl': [(473, 478)]},
    [
        C('text', 'happiness', ar=[253], en=[253], tl=[473]),
        C('text', 'happiness', ar=[254], en=[254], tl=[474]),
        C('text', 'happiness', ar=[255], en=[255], tl=[S(475, None, 'mabuti man o masama.')]),
        C('text', 'happiness', ar=[S(256, None, 'كما قال تعالى:')], en=[S(256, None, 'Allah says:')],
          tl=[S(475, 'Kabilang sa mga bagay', 'katulad ng sinabi ng Allah:')], q=(13, 28, 28)),
        C('text', 'happiness', ar=[S(256, 'وكلما زاد', 'وقوي إيمانه.')], en=[S(256, 'The more the Muslim', 'faith becomes stronger.')],
          tl=[476]),
        C('text', 'happiness', ar=[S(256, 'كذلك ينبغي', 'فقد قال تعالى في كتابه الكريم:')],
          en=[S(256, 'The Muslim should also', 'Allah (SWT) says:')],
          tl=[S(477, None, 'sinabi ng Allah sa maluwalhating Qur’an:')], q=(33, 36, 36)),
        C('text', 'closing', ar=[257], en=[257], tl=[478]),
    ],
    [
        O(T('يعرف أن مَن رضي بالله ربًا وبالإسلام دينًا وبمحمد ﷺ رسولًا ذاق طعم الإيمان',
            'Knows that whoever is content with Allah as Lord, Islam as religion and Muhammad ﷺ as Messenger has tasted faith',
            'Alam na matitikman ang tamis ng pananampalataya ng sinumang nalugod sa Allah bilang Panginoon, sa Islam bilang relihiyon, at kay Muhammad ﷺ bilang sugo'),
          [1], key=True),
        O(T('يعرف أن مَن عبد الله كأنه يراه وأخلص له عاش الحياة الطيبة', 'Knows that whoever worships Allah as if he sees Him, sincerely, lives a good life',
            'Alam na ang sumasamba sa Allah na para bang nakikita Siya, nang taos-puso, ay mamumuhay nang mabuti'), [2]),
        O(T('يعرف أن حرّ المصائب يزول ببرد اليقين والرضا بقدر الله', 'Knows that the pain of calamities is eased by certainty and contentment with Allah’s decree',
            'Alam na naiibsan ang init ng pagsubok sa lamig ng katiyakan at pagkalugod sa tadhana ng Allah'), [3]),
        O(T('يعرف ما يزيد سعادة المسلم: ذكر الله وتلاوة القرآن وتعلّم دينه من المصادر الصحيحة',
            'Knows what adds to a Muslim’s happiness: remembering Allah, reading the Qur’an, and learning his religion from correct sources',
            'Alam ang nagdaragdag sa kaligayahan ng Muslim: pag-alaala sa Allah, pagbasa ng Qur’an at pag-aaral ng relihiyon mula sa tamang mapagkukunan'),
          [4, 5, 6, 7], key=True),
    ],
    [
        match([1], [1], T('أكمل قول النبي ﷺ: «ذاق طعم الإيمان من رضي…»', 'Complete the Prophet’s saying (peace be upon him): “He has tasted the sweetness of faith who is pleased…”', 'Kumpletuhin ang sinabi ng Propeta: “Natikman ang tamis ng pananampalataya ng sinumang nalugod…”'),
              [(T('بالله', 'Allah', 'Allah'), T('ربًا', 'as his Lord', 'bilang kanyang Panginoon')),
               (T('وبالإسلام', 'Islam', 'Islam'), T('دينًا', 'as his religion', 'bilang kanyang relihiyon')),
               (T('وبمحمد ﷺ', 'Muhammad ﷺ', 'Muhammad ﷺ'), T('رسولًا', 'as his Prophet', 'bilang kanyang sugo'))]),
        choose([1], [1], T('ماذا يذوق مَن رضي بالله ربًا وبالإسلام دينًا وبمحمد ﷺ رسولًا؟',
                           'What does the one content with Allah as Lord, Islam as religion and Muhammad ﷺ as Prophet find?',
                           'Ano ang matitikman ng sinumang nalugod sa Allah bilang Panginoon, sa Islam bilang relihiyon at kay Muhammad ﷺ bilang sugo?'),
               [T('طعم الإيمان', 'the taste of faith', 'ang tamis ng pananampalataya'),
                T('حرّ المصائب', 'the pain of calamities', 'ang init ng mga pagsubok'), T('مرارة الحياة', 'The bitterness of life', 'Ang pait ng buhay')]),
        choose([2], [2], T('مَن عبد الله كأنه يراه وأخلص له ولم يرد بعبادته غيره:',
                           'Whoever worships Allah as if he sees Him, sincerely, seeking none other than Him:',
                           'Sinuman ang sumamba sa Allah na para bang nakikita Siya, taos-puso at walang ibang hinangad:'),
               [T('عاش الحياة الطيبة السعيدة في الدنيا، وحسن العاقبة في الآخرة',
                  'lives a happy, blissful life in this world and has the best outcome in the Hereafter',
                  'mamumuhay nang mabuti at masaya sa mundong ito at may mabuting kalalabasan sa hinaharap'),
                T('عاش حياة شقية', 'lives a miserable life', 'mamumuhay nang miserable'), T('لا ينفعه ذلك في الآخرة', 'It does not help him in the Hereafter', 'Hindi ito makabubuti sa kanya sa Kabilang Buhay')]),
        choose([2], [2], T('كيف يعبد المؤمن ربه؟', 'How does the believer worship his Lord?', 'Paano sumasamba ang mananampalataya sa kanyang Panginoon?'),
               [T('كأنه يراه، مخلصًا له', 'as if he sees Him, sincerely', 'na para bang nakikita Siya, nang taos-puso'),
                T('يريد بعبادته غير الله', 'seeking someone other than Allah by it', 'na may ibang hinahangad bukod sa Allah'), T('ليراه الناس', 'So that people see him', 'Upang makita siya ng mga tao')]),
        choose([3], [3], T('بماذا يزول حرّ المصائب التي تقع على المؤمن؟', 'What eases the calamities that befall a believer?',
                           'Ano ang nag-aalis ng init ng mga pagsubok na sinasapit ng mananampalataya?'),
               [T('ببرد اليقين، والرضا بقدر الله، وحمده على أقداره', 'certitude, contentment with Allah’s predestination, and praising Him for what He decrees',
                  'ang lamig ng katiyakan, pagkalugod sa tadhana ng Allah, at pagpuri sa Kanya'),
                T('بالسخط على قدر الله', 'being angry at Allah’s decree', 'ang pagkagalit sa tadhana ng Allah'), T('بنسيان الله', 'By forgetting Allah', 'Sa paglimot kay Allah')]),
        match([3, 4], [3, 4, 5], T('صِل كل عبارة بما يتمّ معناها', 'Match each statement with what completes its meaning', 'Itugma ang bawat pahayag sa kukumpleto ng kahulugan nito'),
              [(T('حرّ المصائب', 'The intensity of calamities', 'Ang init ng mga pagsubok'),
                T('يزول ببرد اليقين والرضا بقدر الله', 'is eased by certitude and contentment with Allah’s decree',
                  'ay naaalis ng lamig ng katiyakan at pagkalugod sa tadhana ng Allah')),
               (T('كثرة ذكر الله وتلاوة القرآن', 'Remembering Allah often and reading the Qur’an', 'Ang madalas na pag-alaala sa Allah at pagbasa ng Qur’an'),
                T('تزداد بهما سعادة المسلم وطمأنينته', 'add to the Muslim’s happiness and reassurance', 'ay nagdaragdag sa kaligayahan at kapanatagan ng Muslim')),
               (T('كلما زاد المسلم من ذكر الله', 'The more the Muslim remembers Allah', 'Sa tuwing pinaparami ng Muslim ang pag-alaala sa Allah'),
                T('زاد ارتباطه بالله وقوي إيمانه', 'the stronger his bond with Allah and his faith', 'lalong tumitibay ang koneksyon niya sa Allah at ang kanyang pananampalataya'))]),
        choose([4], [6], T('من أين يتعلّم المسلم أمور دينه؟', 'Where does the Muslim learn about his religion?', 'Saan natututo ang Muslim tungkol sa kanyang relihiyon?'),
               [T('من المصادر الصحيحة', 'from the correct, reliable sources', 'mula sa tamang mga mapagkukunan'),
                T('من أي مصدر كان', 'from any source at all', 'mula sa kahit anong mapagkukunan'), T('مما يتناقله الناس دون تحقّق', 'From whatever people pass around without checking', 'Mula sa anumang ipinapasa ng mga tao nang hindi sinusuri')]),
        match([4], [6, 7], T('صِل كل عبارة بما يتمّ معناها', 'Match each statement with what completes its meaning', 'Itugma ang bawat pahayag sa kukumpleto ng kahulugan nito'),
              [(T('طلب العلم', 'Seeking knowledge', 'Ang pagsasaliksik ng kaalaman'),
                T('فريضة على كل مسلم', 'is a duty upon every Muslim', 'ay obligado sa bawat Muslim')),
               (T('المسلم مع أوامر الله', 'The Muslim, with Allah’s commands,', 'Ang Muslim, sa kautusan ng Allah,'),
                T('مستسلم منقاد لها، عرف الحكمة منها أو لم يعرف', 'is submissive and yielding, whether he knows the wisdom or not',
                  'ay tumatalima at sumusunod, napag-alaman man ang karunungan nito o hindi')),
               (T('صلى الله وسلم', 'May Allah’s peace and blessings be', 'Ang mga pagpapala at kapayapaan ng Allah ay'),
                T('على نبينا محمد وعلى آله وصحبه', 'upon our Prophet Muhammad, his household and Companions',
                  'mapasa-kay Muhammad, sa kanyang pamilya at sa lahat ng kanyang kasamahan'))]),
    ],
    notes='Second half of «سعادتي في ديني الإسلام», ending with the book\'s closing prayer upon the Prophet ﷺ (card 7). '
          'Verses 13:28 and 33:36 are shown from the Quran database. The hadith are kept as the book quotes them. '
          'The closing line (card 7) is covered by one pair in exercise e8.',
)

LESSONS = [u6l1, u6l2, u6l3, u6l4]
